### ISSUE TITLE
Patient Discharge Summary email template needs update

### ISSUE THREAD

**Issue by mathew-alex** [coronasafe/care#1026]
`patient_pdf_template.html` needs an update. Currently the patient discharge summary email is not working.

view [sentry error log](https://sentry.io/organizations/coronasafe-network/issues/3598437155/?project=5182842&query=is%3Aunresolved)
```
Stack Trace

TemplateSyntaxError
'filters' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
getattributes
i18n
l10n
log
rest_framework
simple_history_admin_list
simple_history_compat
static
staticfiles
tz
```

**Comment by nihal467** [comment]
@sainak can you work on it ASAP
