### ISSUE TITLE
Restrict users list to only superusers

### ISSUE THREAD

**Issue by afzalIbnSH** [coronasafe/care#103]
Now all users can see all.

**Comment by vigneshhari** [comment]
Just Username and Name and District , Nothing else, we might need this to add doctors to facility and staff to facility and so on later on

**Comment by afzalIbnSH** [comment]
Okay

**Comment by afzalIbnSH** [comment]
@tomahawk-pilot re-iterated "One user should not see other users" via slack. @vigneshhari Can you guys discuss and confirm what is to be done ?

**Comment by afzalIbnSH** [comment]
@vigneshhari says;

> Normal users should see other users' id and name only, nothing else

Gonna do this

**Comment by afzalIbnSH** [comment]
#159
