### ISSUE TITLE
Symptoms: Building depth in consultation

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care#1031]
Refer https://github.com/coronasafe/care_fe/issues/3618
cc: @aparnacoronasafe

**Comment by rithviknishad** [comment]
@cp-Coder any updates on this?

**Comment by cp-Coder** [comment]
Yes, the work is almost done. I will open a PR by tomorrow.

**Comment by cp-Coder** [comment]
@rithviknishad I have opened the PR to fix this issue
