### ISSUE TITLE
Update consultation detail's `category` with daily round's `patient_category` when a daily round is created/updated.

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care#1041]
Currently patient category is stored in two places, Consultation Detail and Daily Rounds.
Therefore when a log update is created with a different category other than in consultation, the last consultation's category also should be updated with the log update's category.

cc: @gigincg @vigneshhari

**Comment by gigincg** [comment]
This is unnecessary, the data is already present in consultaiton.last_daily_round
