### ISSUE TITLE
Users API: Structure the unit tests 

### ISSUE THREAD

**Issue by afzalIbnSH** [coronasafe/care#106]
It's vaguely written. Refer https://github.com/coronasafe/care/blob/master/care/facility/tests/test_facility.py.

**Comment by nabhanabdulla** [comment]
@afzalIbnSH , I'll work on the issue as discussed.

**Comment by nabhanabdulla** [comment]
I've refactored the tests.

Now the pre-commit checks is failing due to importing 
`from config.tests.helper import client, user`
 which was already there in the previous test file. 

This is the tail of `git commit` output
```
flake8...................................................................Failed
- hook id: flake8
- exit code: 1
care/users/tests/test_users.py:4:1: F401 'config.tests.helper.client' imported but unused
care/users/tests/test_users.py:4:1: F401 'config.tests.helper.user' imported but unused
care/users/tests/test_users.py:23:46: F811 redefinition of unused 'client' from line 4
care/users/tests/test_users.py:23:54: F811 redefinition of unused 'user' from line 4
```

I think I saw in Slack pre-commit was introduced recently. Any suggestions?

**Comment by afzalIbnSH** [comment]
Those are because of the weird way pytest fixtures work. Can be ignored. Type in `# flake8: noqa` at the top of the file

**Comment by anroopak** [comment]
> sugg

With recent changes, most common fixtures were moved to `conftest.py`, and `#noqa` was put in only that file. Idea is that we keep commonly used fixtures in conftest (or import it in conftest) and that will autoload the fixtures during tests. 

My suggestion is to move common fixtures to `config/tests/fixtures.py`, import them in `conftest.py` and don't ignore flake8 in the individual test files.

**Comment by anroopak** [comment]
> I've refactored the tests.
> 
> Now the pre-commit checks is failing due to importing
> `from config.tests.helper import client, user`
> which was already there in the previous test file.
> 
> This is the tail of `git commit` output
> 
> ```
> flake8...................................................................Failed
> - hook id: flake8
> - exit code: 1
> care/users/tests/test_users.py:4:1: F401 'config.tests.helper.client' imported but unused
> care/users/tests/test_users.py:4:1: F401 'config.tests.helper.user' imported but unused
> care/users/tests/test_users.py:23:46: F811 redefinition of unused 'client' from line 4
> care/users/tests/test_users.py:23:54: F811 redefinition of unused 'user' from line 4
> ```
> 
> I think I saw in Slack pre-commit was introduced recently. Any suggestions?

In the recent changes, a file `conftest.py` has been added in the root. All common fixtures are imported here, and `#noqa` is added to only this file. I suggest that we dont ignore individual files in flake8. Only `conftest` may be ignored.
