### ISSUE TITLE
Reimagining Bedtypes V2

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care#1103]
As a continuation of https://github.com/coronasafe/care_fe/issues/2151 We need to be able to add flags to Bed objects, as well as attach assets to the ConsultationBed Table (For instance if a certain medical equipment(Asset) was used to treat a patient during his visit, that specific ConsultationBed Entry should have a relation to the Asset.

- [ ] BedFlag ThroughTable
- [ ] ConsultationBed-Asset ThroughTable

After the Backend changes are shipped, the UI Issues for these features maybe filed

**Comment by yaswanthsaivendra** [comment]
Is this issue still relevant, can I take up this one??

And as far I understand 2nd part of it, It requires to create a seperate through table ConsultationBedAsset with the schema of something like this,
ConsultationBedAsset:
    consultation_bed  - ForeignKey
    asset  - ForeignKey
    
but i didn't get the purpose of BedFlag through table . can u explain?
