### ISSUE TITLE
Endpoint for pin code details

### ISSUE THREAD

**Issue by Ashesh3** [coronasafe/care#1107]
Related Issue: https://github.com/coronasafe/care_fe/issues/3940

**Describe the solution you'd like**
The backend should have an endpoint which can be used to fetch the State and District from a given pin code.

Options:
1. Proxy http://www.postalpincode.in/Api-Details (can't be used directly since no CORS is supplied by their api)
2. Retrieve the data from a JSON file containing all the pin code details.

**Comment by Ashesh3** [comment]
@vigneshhari Need your input on this.

**Comment by vigneshhari** [comment]
Why is this required? We wont proxy any requests in the backend, we will have to populate the values in the tables we have to store geo structures.

**Comment by sainak** [comment]
I think this is what you are looking for:
```shell
curl -X 'GET' \
  'https://api.data.gov.in/resource/5c2f62fe-5afa-4119-a499-fec9d604d5bd?api-key=579b464db66ec23bdd00000115f15ab447b749065c58768a487d76bb&format=json&filters%5Bpincode%5D=400001' \
  -H 'accept: application/json'
```
ref: https://data.gov.in/apis/5c2f62fe-5afa-4119-a499-fec9d604d5bd
the public api key is good for upto 10 records per request so we can directly use this in the frontend
