### ISSUE TITLE
Facility Status Monitoring

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care#1108]
We need to use Celery to ping the Facility Middleware & Integrated Assets, to setup a Status Page within CARE

The following items can be monitored, each of these can be taken up as separate issues, in the given order.

- [ ] Facility Uptime: Ping middleware base_url
- [ ] Middleware: Camera Status URL 
- [ ] Middleware: Medical Device Status URL 
- [ ] Camera Asset Uptime
- [ ] Medical Device Asset Uptime
- [ ] Notification/Webhooks for Downtime Notification

cc: @vigneshhari Please add suggestions on what's the best way to store uptime information

**Comment by vigneshhari** [comment]
We can store a log table to store the ping results, if this data is not needed for long we can keep it in redis. If we choose to use the DB, we can delete it after a given number of days.

**Comment by sainak** [comment]
completed in #1454
