### ISSUE TITLE
Asset Update APIs are throwing error 500

### ISSUE THREAD

**Issue by skks1212** [coronasafe/care#1168]
**Describe the bug**

**To Reproduce**
1. Go to asset update page for any asset
2. Update any detail
3. Click save

**Expected behavior**
Details should save without any problems.

**Screenshots**
![image](https://user-images.githubusercontent.com/23238460/215377214-6fdd4499-caa0-4b66-a084-537ba095e454.png)

**Comment by cp-Coder** [comment]
@skks1212 A similar issue has already been opened #1164
