### ISSUE TITLE
Skills api is not working as expected

### ISSUE THREAD

**Issue by Pragati1610** [coronasafe/care#1172]
**Description of the bug**
When we update skills of a user, all users skills gets updated with the same skills

**To Reproduce**
1. add a new skill to a user
2. check skills of other users
3. you will find other user skills have also been updated

**Expected behavior**
Skills and users should have a many to many relationship and each user should have a separate set of skills

**Comment by khavinshankar** [comment]
There need to be a follow up on the frontend as well as state is not updating properly
