### ISSUE TITLE
Migrant labor management system.

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care#118]
# Should Support Registration
- [ ] name
- [ ] state of origin
- [ ] employer/contractor (optional) 
- [ ]  current local residence in kerala
- [ ] living faculty (has toilet, clusterd living, has masters, cooking - self /outside, has labor department offical reached you.
- [ ]  ward wise data
- [ ] location - latitude and longitude 
- [ ]  can speak malayalam - yes / no
- [ ]  can speak other languages - _ _ _ _ _

**Comment by aswinmohanme** [comment]
I'll be working on this

**Comment by vigneshhari** [comment]
@aswinmohanme will you be working on django ?

**Comment by aswinmohanme** [comment]
Rails pore ?

**Comment by vigneshhari** [comment]
we will keep this in our current DB, that makes more sense right?

**Comment by aswinmohanme** [comment]
Yeah, but how do we plan to implement this. 

Where do we get the information on the People who request food. We could add a is_migrant field and then use that to create an association with a migrant details maybe

**Comment by tomahawk-pilot** [comment]
endanelum we have to deploy tommorow before its a communal issue .

**Comment by vigneshhari** [comment]
@bodhish are you sure this is the confirmed model that we need ? and only admins/staff can add a new woker ?

**Comment by bodhish** [comment]
They may need a self reg form, the challenge here is that, we will need to translate it. If better if a staff / volunteer does the job.

We can do it in the care app but i am off an opinion let's separate it out as it has no connection to covid. This would be system for reg and tracing migrant workers across the state.

The challenges of splitting out is that, we need to seed state, district and ward wise data.

@Vignesh you can take a call on this.

**Comment by tomahawk-pilot** [comment]
+1 on seperate db . and a seprate app. so if other states want to implement it they can just take it

**Comment by bodhish** [comment]
@aswinmohanme Lets move it out into a seperate app

**Comment by aswinmohanme** [comment]
In that case https://github.com/coronasafe/migrantmanagement

**Comment by bodhish** [comment]
moved to https://github.com/coronasafe/migrantmanagement

**Comment by vigneshhari** [comment]
Closing this issue
