### ISSUE TITLE
Patient filter: Add `None` option for Last admitted to Bed filter to filter patients that are admitted but has no bed assigned

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care#1184]
In Advanced filter on the patient list, https://care.coronasafe.in/patients
The last admitted to bed type filter is not in sync with the updated bed management.

The problem is, how do we search for a patient that is admitted, but for which no bed is allocated yet.

**Comment by JahnabDutta** [comment]
Hey, I was going through this issue and I have some doubts.
I found that 'Admitted to(Bed Type)' filter in frontend takes it's options from a constant object called ADMITTED_TO in src/Common/constants.tsx. So, along with the backend, that will also need to be modified right?
Also, in the backend, we need to append a new choice in the BedTypeChoices and that should suffice right?

**Comment by rithviknishad** [comment]
Hey @JahnabDutta 

Yes, both the backend and front end needs to be updated to include the `None` filter option.

About the backend, appending a new choice to `BedTypeChoices` may not be the right solution as `None` is not a valid bed type. Say you have a bed, its type will never be None.

However, what we need to achieve is, to check whether a Patient's Last Consultation's Current Bed is None/null or not.

cc: @vigneshhari
