### ISSUE TITLE
Missing proper validation for phone number in patient registration form

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care#1243]
**Describe the bug**
When we register a patient and enter a number say with one digit missing, the patient is still getting created correctly. However, if one digit is missing for emergency phone number, it's validation works fine. 

**To Reproduce**

1. Create a patient
2. Enter phone number with digits missing

**Expected behavior**
Phone Number also should be validated correctly, similar to Emergency Phone Number

**Screenshots**
![image](https://user-images.githubusercontent.com/25143503/230657080-c864d79d-ddf8-4811-9086-9f59e20e991e.png)

![image](https://user-images.githubusercontent.com/25143503/230657536-319d5cbd-de7e-4b2a-9d84-85bc87526d05.png)

**Comment by gitone912** [comment]
can i start working on this?
