### ISSUE TITLE
District Level Access User Group

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care#126]
Need to create a usergroup that has access to all the facilities in a certain district. Will be used to provide accounts to district collectors.

**Comment by anroopak** [comment]
@bodhish planning to add a new user type.

**Comment by anroopak** [comment]
@gigincg @bodhish should they be allowed to update, like the super users?
I am assuming yes, for now.

**Comment by bodhish** [comment]
Yes, the use case is to allow district admin to have an overview of the entire system and correct details.
