### ISSUE TITLE
Capture the following details for each hospital. 

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care#127]
# OP TRIAGE

TOTAL PATIENT VISITED IN CORONA TRAIGE | TOTAL NO.OF PATIENT ADVISED HOME QUARANTINE | TOTAL NO.OF PATIENTS UNDER ISOLATION | TOTAL OF PATIENTS REFFERED
-- | -- | -- | --

**Comment by tomahawk-pilot** [comment]
Per day alle

**Comment by bodhish** [comment]
yes

**Comment by anroopak** [comment]
### Models
```
FacilityPatientStatsHistory
facility_id -> refers Facility
entry_date -> date of the data entry (default will be today, can be overrridden)
num_patients_visited -> "TOTAL PATIENT VISITED IN CORONA TRAIGE"
num_patients_home_quarantine -> "TOTAL NO.OF PATIENT ADVISED HOME QUARANTINE"
num_patients_isolation -> "TOTAL NO.OF PATIENTS UNDER ISOLATION"
num_patient_referred -> "TOTAL OF PATIENTS REFFERED"
```

### APIs
`GET /facility/{id}/patient_stats/` - can support date filter
`POST /facility/{id}/patient_stats/` - will create or update for the date mentioned
```
{
  "entry_date": "",
  "num_patients_visited",
  "num_patients_home_quarantine",
  "num_patients_isolation",
  "num_patient_referred"
}
```
@bodhish @tomahawk-pilot Confirm the APIs please.

**Comment by tomahawk-pilot** [comment]
@bodhish is this data entered manually per day ?

**Comment by bodhish** [comment]
Yes
