### ISSUE TITLE
Map patients to facilities

### ISSUE THREAD

**Issue by afzalIbnSH** [coronasafe/care#128]
Create a many to many mapping as:
- A facility will have multiple patients
- More importantly, we need history of a patient's move between facilities. Use a flag to denote the current facility a patient is in.

**Comment by afzalIbnSH** [comment]
DB Proposal:

FacilityAdmission

- facility_id, int referencing Facility, required
- patient_id, int, referencing PatientRegistration, required
- admission_date, timestamp, required
- is_active, boolean, "If the patient is currently in the facility"
- discharge_date, timestamp

Constraints:
- partial uniqueness => patient_id where is_active = True
- check ( (is_active) or (discharge is not null) )

**Comment by afzalIbnSH** [comment]
APIs:
- Admit patient to facility => `PUT /facility/{id}/patient/{id}/`
- Discharge patient from facility => `DELETE /facility/{id}/patient/{id}/`
- List patients in a facility => `GET /facility/{id}/patient/`

Also,
- Return facility_id in `GET /patient/` and `GET /patient/{id}`. It should be the id of the facility that the patient is currently admitted to, if he is.

**Comment by afzalIbnSH** [comment]
@anroopak @vigneshhari Please review the db and API proposals. I'll get to dev late night or early morning. Got some office stuff to do. Feel free to move it to your plates if this is required earlier.

**Comment by anroopak** [comment]
@afzalIbnSH In the Patient Detail, do you want to show the history?

**Comment by afzalIbnSH** [comment]
> In the Patient Detail, do you want to show the history?

@anroopak Only if there is such requirement? Or I can accept a query param, say, `history=<bool>` and return history only if true, to avoid unnecessary db load.

**Comment by bodhish** [comment]
A few additions required. 
We cannont assume that the patient will be admitted in a facility. 
Their are 3 outcomes for a patient who visits a hospital

1. They may be asked to go home for home isolation
2. They would be asked to get admitted in the hospital
3. They would be reffered to another facility. 

We should have an option to capture these detials. 

Ex: A patient asked to be in home isolation will have to be followed up. (This can be a manuel process for now) We should store these information so that, the next time when they visit the same facility the doctor will have better data

Basic patient detailes has to captured for all the 3 cases. The outcome will be one of the 3.

**Comment by afzalIbnSH** [comment]
@anroopak Added a separate endpoint for patient history:
- GET /patient/{id}/history/

**Comment by afzalIbnSH** [comment]
@bodhish Update db:

Table => `patient_consultation`

Columns:
```
facility_id, int referencing facility, required
patient_id, int, referencing patient_registration, required
prescription, char, options -> ("home_isolation", "admission", "referral"), required
referred_to, int referencing Facility
admitted, boolean
admission_date, timestamp
discharge_date, timestamp
```

Constraints:
```
CHECK (IF (prescription = "another_facility") THEN (referred_to IS NOT NULL))
CHECK (IF (admitted) THEN (admission_date IS NOT NULL))
```
I'm removing the `is_active` flag and the partial uniqueness constraint that said `unique(patient_id) where is_active = True`. As @anroopak pointed out in the PR I raised, we can't expect these data to be perfectly filled. We'll just believe a facility admin when he says a patient has consulted him. We'll assume the latest entry as a patient's present status and the entries in order as his history. Makes sense ?

**Comment by afzalIbnSH** [comment]
@anroopak Gonna push a separate PR just with the db

**Comment by afzalIbnSH** [comment]
Db: #142

**Comment by afzalIbnSH** [comment]
APIs:
- Add consultation => `POST /facility/{id}/consultation/`
- Update consultation => `PUT /facility/{id}/consultation/{id}/`
- List consultation  => `GET /facility/{id}/consultation/`
- Patient history => `GET /patient/{id}/history/`

**Comment by afzalIbnSH** [comment]
APIs PR: https://github.com/coronasafe/care/pull/147
