### ISSUE TITLE
UI Changes

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care#13]
# Home Page
- [x] Rename hosptial `SIGN UP` to `Hospital Administrator Signup`

# Staff Sign Up form
- [x] Rename `Phone Number` to `10 digit mobile number`
- [x] Replace submit button text with `Hosital Administrator Signup`

# Facility Register form (facility/create/)
- [x] Label - name should be changed to `Name of Hospital`
- [x] Label - address should be changed to `Enter Hospital Address`
- [x] Submit button text - `Click to Submit Hospital Details`

# Capacity page
- [x] Add title `Enter Your Hospital Capacity`
- [x] Add the following description 
```
The Chief Ministers's office request to know imformation about  total capacity and current Utlisation of Normal Beds, ICU Beds and Ventilators in your Hospital

1. Normal Beds
2. ICU Beds
3. Ventilators
```
- [x] Rename room type to `Bed Type`
- [x] Rename capacity to `Total Capacity`
- [x] Rename current_capacity tp `Current Capacity Utilisation`
- [x] Replace Button text ` Save add more Bed Types`

# Doctors Page (/doctorcount/add/)
- [x] Title - `Add the number of doctors in different specialization`
- [x] Seed default values for doctor specialization, Use the folllowing
```
General Medicine, Pulmonology, Critical Care, Paediatrics
```

# Facility show
- [x]  Rename `update` button text  to `Edit`

# Facility Index
- [x] Add title - The Chief Ministers's office request to know *Live Data*
- [x] List the facility as a big card as its going to be mostly one facilty per user.

**Comment by rejuls** [comment]
First 3 done. Third checked because all signup pages now have type in the heading itself.

**Comment by aswinmohanme** [comment]
I have added some JS to add default classes to all input elements, no need to add them by hand anymore.

**Comment by aswinmohanme** [comment]
Also how to access facility/create, should I create an account or is there a test account

**Comment by aswinmohanme** [comment]
Also what are the opinions on left aligning the UI. We could increase the discoverabiility.

**Comment by bodhish** [comment]
You can take a call on UI/UX
