### ISSUE TITLE
Periodically hard delete Notification records that are older than 90 days.

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care#1320]
**Is your feature request related to a problem? Please describe.**
The notification table is huge. We don't want notification records older than 90 days.

**Describe the solution you'd like**
Periodically hard delete records from Notifications table that are older than 90 days.

**Comment by yaswanthsaivendra** [comment]
Hey , i would like to take up this one.

As far i understand, we would need to create a periodic_task using celery that would run maybe every midnight to delete all the notifications that are older than 90 days.

but can we specify a few things for me,
- Like what would be a great place to create this scheduler function(maybe inside a new file - `care/facility/tasks/notification/delete_older_notifications.py`)??
- period/Time to run the task(maybe every midnight)??
- I cant see a `created_at` field so do we need to decide this 90 days older on basis upon `read_at` field which exists in Notification table or add a `created_at` field to the table??

**Comment by rithviknishad** [comment]
1. Yes, that place looks right!
2. Yes, every midnight should be fine.
3. Yes, based upon `created_date` field which is when the notification record has been created.

**Comment by rithviknishad** [comment]
cc: @yaswanthsaivendra
