### ISSUE TITLE
Add CSV support for the asset import/export

### ISSUE THREAD

**Issue by patelaryan7751** [coronasafe/care#1327]
**Is your feature request related to a problem? Please describe.**
All exports have backend support for CSV so there is a need to do the same for asset  
refer to https://github.com/coronasafe/care_fe/issues/5483

**Comment by gitone912** [comment]
I am doing this one so much thanks I will comment the procedure soon

**Comment by gitone912** [comment]
so do we need to add two buttons like one for import csv and one for export csv and make their features same as its working for xl import json export?
@rithviknishad

**Comment by rithviknishad** [comment]
Yes! Have a look at patient csv export/import. It should be similar, just that this is in addition to JSON for assets.

**Comment by gitone912** [comment]
there is json export already , i have to enable a csv export , so i can add a button and whenever user clicks on it ,it download the csv right just like its downloading json now 
i need to remove json download or its fine?

**Comment by rithviknishad** [comment]
@gitone912 This is a backend issue. Currently our backend does not support CSV export for Assets. JSON export is handled in front-end. However, CSV exports are handled in backend.

Do not remove JSON support. JSON support is important, CSV support is just a good to have.

**Comment by gitone912** [comment]
@rithviknishad thanks for explaining
so can i add a export button of csv and perform the csv task in backend and let user download the csv file ?

**Comment by rithviknishad** [comment]
@gitone912 have u referred to the first comment's link? We already have the front-end changes. You just need to add backend support for the same to function.

**Comment by gitone912** [comment]
<img width="1440" alt="Screenshot 2023-06-03 at 12 20 14 PM" src="https://github.com/coronasafe/care/assets/96557682/71c9e2d7-c07e-44f4-9c4e-47c14d940248">
I saw a export function external result which is exporting in csv format but its working in js there 
do I need to do it in Django backend or js there ?

**Comment by patelaryan7751** [comment]
Hey @gitone912 are you still working on this?

**Comment by nihal467** [comment]
it is already solved in the platform ( #1592  ), so closing the related PR & issue

**Comment by sainak** [comment]
closed in https://github.com/coronasafe/care/pull/1592
