### ISSUE TITLE
Ambulance: add has_free_service & price_per_km

### ISSUE THREAD

**Issue by afzalIbnSH** [coronasafe/care#133]

**Comment by rejuls** [comment]
@afzalIbnSH there was already an open issue #115  and I have pushed a commit based on that. It doesn't have the boolean field though. Do pull and continue your work.

**Comment by afzalIbnSH** [comment]
integer field is not a good fit to store money. I think I'll use something more fitting.

**Comment by anroopak** [comment]
@afzalIbnSH We use this strategy in our FinTech company.
https://medium.com/selency-tech-product/your-balance-is-0-30000000004-b6f7870bd32e
DecimalField also may be good.
