### ISSUE TITLE
Fix existing Unit Tests & Ensure they are running in Github Actions

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care#1367]

**Comment by cp-Coder** [comment]
I would like to work on it. Please assign it to me.

**Comment by vigneshhari** [comment]
Current unit tests work as expected and run successfully in GitHub actions, but they test little to nothing, you can treat this as an EPIC and create sub-tickets for each module and add tests for them. We need to test all edge cases and all authorization edges. Lemme know if you need to discuss this over a call.

**Comment by cp-Coder** [comment]
Thanks Vignesh

**Comment by yaswanthsaivendra** [comment]
Creating Tests for the whole code base is itself a huge task. So, Lemme know if I can make some part of contributions to this issue.

**Comment by cp-Coder** [comment]
Sure

**Comment by cp-Coder** [comment]
Closed in favour of #1372
