### ISSUE TITLE
Create a system to store details on samples taken

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care#137]
Their should be an option to capture details of samples taken in each facility. 
This should be associated with a patient record.
Sample can be taken multiple times.
Possible outcomes for a sameple is [Positive, Negative, Resutl Awaiting]
Date of sample taken should be recorded

**Comment by anroopak** [comment]
### Model: Sample
```
facility_id
patient_id - refers to PatientRegistration
result - enum
date_of_sample
date_of_result
```

### APIs
POST /sample/
```
Request:
{
  "facility": id,
  "patient": id,
  "date_of_sample": 
   "result": (int option), // supporting this feature so that previous data can be entered. if empty "Result Awaiting"
  "date_of_result":  // nullable field
}

Response
{
   "id":  // sample id,
    ... other fields
}
```

PATCH /sample/:id/
```
 "date_of_sample": 
   "result": (int option), 
  "date_of_result":  // nullable field
```

@bodhish please confirm

**Comment by krishnanunnir** [comment]
Hey, I would like to help out

**Comment by anroopak** [comment]
This was completed. Closing.
