### ISSUE TITLE
Random 502 on `api/v1/auth/login/`

### ISSUE THREAD

**Issue by sainak** [coronasafe/care#1421]
Randomly getting 502 on login endpoint 
<img width="339" alt="image" src="https://github.com/coronasafe/care/assets/46787056/32b9b075-8bf5-4268-9be3-bf52e3265bb3">
Response:
```html
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
```

Errors reported on ELB:
<img width="1485" alt="image" src="https://github.com/coronasafe/care/assets/46787056/c39c230c-0a0c-482f-a4ae-9923ba3448c5">

Possible cause: scaling config change on 16/6

**Comment by sainak** [comment]
@mathew-alex has increased the number of scaling replicas to 4

**Comment by mathew-alex** [comment]
Enabled access logs for the load balancer and increased the size of individual containers. will check if that resolves the issue.

**Comment by rithviknishad** [comment]
Not facing this issue for past one week, right?
