### ISSUE TITLE
Update api schema for password reset endpoints

### ISSUE THREAD

**Issue by sainak** [coronasafe/care#1434]
Override the default forgot password and password reset endpoints and:
- [ ] Add relevant fields to serializers
- [ ] update test cases

**Comment by GeekGawd** [comment]
What fields need to be overriden?

**Comment by sainak** [comment]
You can take a look at the API requests in the test cases for password reset and update the endpoints accordingly

**Comment by itxsoumya** [comment]
can you this issue to me?

**Comment by itxsoumya** [comment]
@sainak any update?
