### ISSUE TITLE
Update Model to add Educational Institutions

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care#146]
We need to add educational institutions under 2 separate categories, namely Arts and Science Colleges and Engineering Colleges. This would mean that we should create 2 additional facility types for the same. 

Also to add the facilities of hospitals, we already have Hostels as a General Room Type, We will need the following Room Types additionally:  Mens Hostel; Womens Hostel; Others;

Also, the Rest API that accepts the batch upserts should allow adding to facilities with these parameters

Edit: Have decided to use the Buildings Model to store the details of Educational Institutions and their buildings.  Mens Hostel; Womens Hostel and  Others would be names of buildings and the Number of Rooms and Building Count/Number (New field in Buildings table Already created by @vigneshhari ) Can be used to store this Information. Resulting in College Name/Type of College -> Stored as FacilityName/Facility Type,  Buildings -> Rows in Buildings Table, Number of Buildings/Combined Capacity of Buildings -> Using Fields Number of Rooms and Number of Buildings fields in the Building Table.

Need to Create APIs for use with Retool to allow upsert towards this model.

**Comment by anroopak** [comment]
How to handle the current info about Hostel Rooms?

**Comment by gigincg** [comment]
Added Edits to Conform to the decisions made to incorporate the details of colleges into the existing Models.
