### ISSUE TITLE
Missing migration for the daily round model update

### ISSUE THREAD

**Issue by Bhavik-ag** [coronasafe/care#1499]
Problem

- Missing migration for the daily round model update done in https://github.com/coronasafe/care/commit/2e1210839ed45b13e21e780b79fb84487c80dcd1

**Comment by rithviknishad** [comment]
@sainak should we add a CI to test if any migrations are missing in the future?

**Comment by rithviknishad** [comment]
cc: @vigneshhari

**Comment by sainak** [comment]
There is a precommit hook for it
We can add that

**Comment by Ashesh3** [comment]
> There is a precommit hook for it
> We can add that as well

Do we already have that? I already have precommit hooks installed and I don't remember seeing any such error which missing the migration..

**Comment by rithviknishad** [comment]
I think he meant that "there is a pre-commit hook that can be configured"

**Comment by rithviknishad** [comment]
@sainak I tried running a local pre-commit to run `./manage.py makemigrations --check --dry-run`

This works fine when running via CLI (`git commit -m ...`), but fails to run when commiting from vscode git extension. Failed to import Django.

**Comment by Ashesh3** [comment]
> @sainak I tried running a local pre-commit to run `./manage.py makemigrations --check --dry-run`
> 
> This works fine when running via CLI (`git commit -m ...`), but fails to run when commiting from vscode git extension. Failed to import Django.

Does the vscode git command run outside the context of the current virtual environment, hence the failing import?

**Comment by rithviknishad** [comment]
it has got something to do with this actually

<img width="553" alt="image" src="https://github.com/coronasafe/care/assets/25143503/ba30e53f-d229-412f-886c-ad4b0bab476b">

**Comment by sainak** [comment]
> > @sainak I tried running a local pre-commit to run `./manage.py makemigrations --check --dry-run`
> > 
> > This works fine when running via CLI (`git commit -m ...`), but fails to run when commiting from vscode git extension. Failed to import Django.
> 
> Does the vscode git command run outside the context of the current virtual environment, hence the failing import?

Yes precommit creates virtual env for each hook and uses that by default
If you want to run checks with local packages use the system type for hooks
