### ISSUE TITLE
Limit the use of ALL CAPS 

### ISSUE THREAD

**Issue by aswinmohanme** [coronasafe/care#15]
We are currently using ALL CAPS very liberally, although it is an attention grabber, it makes the UI look polluted and overwhelming. 

We should limit the Use of ALL-CAPS or try to remove emphasis by reducing the size of the all caps elements.

Also is the all caps used for transalation. We could put normal text inside elements and use the `uppercase` tailwind class to style them to ALL CAPS.

**Comment by rejuls** [comment]
I tried the normal casing for the headings and it looked really ugly with the long headings. I personally feel capitals are better for the titles.

**Comment by rejuls** [comment]
@bodhish ?

**Comment by bodhish** [comment]
I would not recommend all caps. But it's a design call. You guys figure out 😀

**Comment by aswinmohanme** [comment]
Kind of makes everything stressful, use cheiyuvarke already nalla stress aarikum

**Comment by rejuls** [comment]
Okie. Will change.
