### ISSUE TITLE
Update for sample flow

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care#151]
Can we have few changes. This is the flow used in ernakulam.

1.  In the Hospital Care system, there needs to be a new Form for Request a Corona Sample Test      
2.  The District Nodal Lab Officer should have a login to approve or deny this request and the Hospital has to see the Status of Request.  
3.  Once the Hospital takes the sample of those which are “Approved”, they mark a status as “Send to Sample Collection System”  
4.  District Administrators can then mark the “Status” as “Received and forwarded to the Lab”
5.  The State Lab has to have an admin login where they can see district wise data of each sample received for the day.  
6.  They can update the results of each sample as “Positive”, “Negative” or “Invalid”.  
7.  The Status for each district should be seen on a dashboard in real-time.      
8.  CMO should have a dashboard to see Real-Time status of all Districts.

**Comment by anroopak** [comment]
So the new APIs need would be
1. API to submit a request for taking sample. Question: Who will submit this request? Should a patient be registered for this?
2. API for District Nodal Officer to list, approve/deny
3. API to mark as "Sent to Sample Collection"
4. API to mark as "Received and Forwarded"
5. API to mark the result of the sample - Question: What do you mean by "Invalid", how a sample be Invalid? Just curious. 

@bodhish can you tell me what all details you need on the dashboards?

**Comment by bodhish** [comment]
1. Faculty admin will have an option to create a sample collection request inside patient view.

2. Their is an Invalid status reported from the testing center which means they are unable to classify it as positive /negative

**Comment by anroopak** [comment]
POST /patient/{id}/patient_sample/
Request
{
    "facility": id
}

Response {
    "id": 1, // sample id -> with default approval status as pending
    "approval_status": "APPROVED/DENIED/AWAITING"
}

-----------------

// Approval
PATCH /patient/{id}/patient_sample/{id}/
Request {
    "approval_status": "APPROVED/DENIED"
}

// Mark as sent to Sample Collection
PATCH /patient/{id}/patient_sample/{id}/
Request {
    "status": "SENT_TO_COLLECTON_CENTRE"
}

// Mark as sent to Forwarded
PATCH /patient/{id}/patient_sample/{id}/
Request {
    "status": "RECEIVED_AND_FORWARED"
}

// Mark as sent to Received at lab
PATCH /patient/{id}/patient_sample/{id}/
Request {
    "status": "RECEIVED_AT_LAB"
}

// Mark as sent to Received at lab
PATCH /patient/{id}/patient_sample/{id}/
Request {
    "result": "POSITIVE/NEGATIVE/INVALID"
}
