### ISSUE TITLE
Patient tele-consultation

### ISSUE THREAD

**Issue by afzalIbnSH** [coronasafe/care#153]
@bodhish Is a tele-consultation always linked to a facility?

**Comment by bodhish** [comment]
No, Its a centralised facility. 
A district will have a call center that address these issues

**Comment by vigneshhari** [comment]
does the patient call the center or the other way around ? if so who gets to update the data @bodhish

**Comment by bodhish** [comment]
@vigneshhari its the other way around. Lets hold this feature for a day so that i have a better clarity on the ground process.
