### ISSUE TITLE
Assigning patient to multiple doctors/nurses in consultation

### ISSUE THREAD

**Issue by print-Sathvik** [coronasafe/care#1647]
**Is your feature request related to a problem? Please describe.**
This is related to coronasafe/care_fe#6276

**Describe the solution you'd like**
In the frontend form and post request of consultation I made the following changes:
removed these attributes:

- `assigned_to` (type: string)
- `assigned_to_object` (type: UserModel | null)

added these attributes:

- `doctor_assigned_to` ( type: UserModel[ ] ) - an array that can have up to 3 doctor objects
- `staff_assigned_to` ( type: UserModel[ ] ) - an array that can have up to 2 nurse objects

Changes should be made in the backend to receive the data in this format in consultation form

**Comment by Shahbaz898414** [comment]
I would like to work on this issue

**Comment by Ashesh3** [comment]
@Shahbaz898414 Issue is already assigned and PR is already open for it 😅 Feel free to take up another issue!

https://github.com/coronasafe/care/pull/1900

**Comment by Ashesh3** [comment]
Closing in favor of https://github.com/coronasafe/care_fe/issues/6276
