### ISSUE TITLE
Provide both id and text in API response

### ISSUE THREAD

**Issue by SandeepThomas** [coronasafe/care#169]
API endpoint: /facility/{facilityId}/capacity/
Change: Provide both room_type id and text in the API response

API endpoint: /facility/{facilityId}/hospital_doctor/
Change: Provide both area id and text in the API response

**Comment by anroopak** [comment]
`room_type` => ID
`room_type_text` => text

Would this kind of response be good enough?

**Comment by qburst-sandeep** [comment]
Yes @anroopak

**Comment by SandeepThomas** [comment]
Yes @anroopak
