### ISSUE TITLE
Fix cors headers in prod

### ISSUE THREAD

**Issue by sainak** [coronasafe/care#1702]
currently we are sending multiple hostnames in acao header instead only the requesting host header should be returned

this is due to the acoa header hardcoded in nginx config in infra deployments

https://github.com/coronasafe/infra_template/blob/0686194e6cdc73c579971c0afa006772166d8446/configmaps/nginx.yaml#L113

but this should be handeled by django-cors-headers middleware
https://github.com/adamchainz/django-cors-headers

- [ ] #1703
- [ ] update all instances to include the correct hostnames
- [ ] remove hardcoded hostname from nginx config

**Comment by itxsoumya** [comment]
Hello, can I work on this issue ?
