### ISSUE TITLE
Enhance Facility list API

### ISSUE THREAD

**Issue by vigneshhari** [coronasafe/care#171]
Let the `GET api/v1/facility` API accept a couple of query params, `search_text` and `all`.

- `all` -> Boolean, if true should return every facility to all logged in users with just their id, name and district
- `search_text` -> str, Search on the facility's properties.

Make sure the API is paginated

**Comment by sandeepsajan0** [comment]
I am working on it.

**Comment by anroopak** [comment]
@afzalIbnSH  `search_text` would it search on every property? That would be too much computation. 

I would prefer proper filters as documented in - https://django-filter.readthedocs.io/en/master/ref/filters.html

**Comment by vigneshhari** [comment]
@anroopak we would need to create a search vector i think in Postgres

**Comment by vigneshhari** [comment]
@sandeepsajan0 have you finished it ?

**Comment by sandeepsajan0** [comment]
I have done with `all` boolean query param. I am just making a PR.

**Comment by afzalIbnSH** [comment]
Yep. A search vector should be efficient enough for us.

**Comment by afzalIbnSH** [comment]
We don't need the `all` Boolean any more right @vigneshhari ? `/facility/list_all` is open to all.

**Comment by vigneshhari** [comment]
Yes

**Comment by sandeepsajan0** [comment]
okay, then I am starting to work on search_text param.

**Comment by vigneshhari** [comment]
I am creating another issue with updated requirements, no worries

**Comment by afzalIbnSH** [comment]
@sandeepsajan0 Make sure to use vectors. Also order by relavancy. Refer https://docs.djangoproject.com/en/3.0/ref/contrib/postgres/search/#searchrank

**Comment by afzalIbnSH** [comment]
@sandeepsajan0 Have you made progress on this? The search should happen on the below fields; `name, district name, state name`. Add a query param `search_text` to `GET /facility`.
