### ISSUE TITLE
Difficulty in setup of the project

### ISSUE THREAD

**Issue by sandeepsajan0** [coronasafe/care#173]
I'm not able to install postgres-scripts for postgreSQL version 12.1. 
By `psql --version` I am getting this `psql (PostgreSQL) 12.1 (Ubuntu 12.1-1.pgdg16.04+1)`
`sudo apt install postgresql-12.1-postgis-scripts`
I'm using the above command to install scripts. but I'm getting this
```
E: Unable to locate package postgresql-12.1-postgis-scripts
E: Couldn't find any package by glob 'postgresql-12.1-postgis-scripts'
E: Couldn't find any package by regex 'postgresql-12.1-postgis-scripts'
```
I have also tried only with the major
`sudo apt install postgresql-12-postgis-scripts`
I got error
`E: Package 'postgresql-12-postgis-scripts' has no installation candidate`

**Comment by farisshajahan** [comment]
Your psql version is not the same as your postgres version.
To get your postgres version, login to postgres and execute `select version();`
Then use the major version number from that to install postgis scripts.

**Comment by sandeepsajan0** [comment]
Solved with `sudo apt install postgresql-<postgres-version>-postgis-3-scripts`
