### ISSUE TITLE
Telegram Chat Bot

### ISSUE THREAD

**Issue by somaraj** [coronasafe/care#178]
Hi Team,
You are really doing a great job. 
I just created a base version of **Telegram Chat Bot**, if this could help the project/public in some way then I am happy to continue the development and make the bot production ready. Kindly let me know your thoughts. Looking forward to join hands with the team and **break the chain**

Bot Name: **Corona Safe KL**
Username: **@coronasafe_kl_bot**

**Note:** this is just an preview version with very minimal functionality.

![bot_info](https://user-images.githubusercontent.com/17797942/77856001-e9c16e80-7211-11ea-8ee6-a86e0614cfd0.jpg)

![start](https://user-images.githubusercontent.com/17797942/77856014-fba31180-7211-11ea-8615-65e1c84253d0.jpg)

![option_1](https://user-images.githubusercontent.com/17797942/77856017-ffcf2f00-7211-11ea-948e-5f470a4cf134.jpg)

![option_2](https://user-images.githubusercontent.com/17797942/77856019-0493e300-7212-11ea-88cd-88f1b5ad06f9.jpg)

![option_3](https://user-images.githubusercontent.com/17797942/77856022-08c00080-7212-11ea-9acd-614c8b4de30d.jpg)

![option_4](https://user-images.githubusercontent.com/17797942/77856026-0f4e7800-7212-11ea-8636-f1f946b733cd.jpg)

**Comment by bodhish** [comment]
@aswinmohanme please review this

**Comment by aswinmohanme** [comment]
Nice work @somaraj. Where is the repo hosted ? I'm trying to build a Whatsapp bot, it would be awesome to integrate these features there as well

**Comment by vigneshhari** [comment]
Closing this issue, please move the issue to https://github.com/coronasafe/features/issues
