### ISSUE TITLE
Add environment variable to disable summarization cron tasks

### ISSUE THREAD

**Issue by sainak** [coronasafe/care#1800]
- [ ] Add environment variables to disable specific summarization tasks, they should be allowed to un by default
- [ ] Update docs

https://github.com/coronasafe/care/blob/ef73d9368fc8df775688c497acbd4e17fd9ba1a2/care/facility/tasks/__init__.py#L23-L47

the variable names should be in the pattern `TASK_SUMMARIZE_*`

**Comment by amjithtitus09** [comment]
Hey @sainak can you assign me this issue?

**Comment by amjithtitus09** [comment]
@sainak Could you please share the link of the doc to be updated?

**Comment by sainak** [comment]
@amjithtitus09 there is no doc for environmnt variables but you can create a new file under /docs/django-configuration and add the new variables, with a brief description and examples under the environment variables section
