### ISSUE TITLE
Custom Migration to clean no input values as `null` in Daily Rounds table

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care#1810]
Related to https://github.com/coronasafe/care_fe/issues/6985

## Tasks

- [ ] Migrate all fields in daily rounds that has zero values to be `null`.
- [ ] Migrate all blood pressure fields that are less than or equal to 0 to be `null` (reason: https://github.com/coronasafe/care_fe/pull/6954/commits/fc77784f65d36783e78a67cc62e4c1372677ad3d)

**Comment by aeswibon** [comment]
I would like to work on it.

**Comment by aeswibon** [comment]
@aparnacoronasafe, Can you confirm whether zero can be a valid value in blood pressure fields?

**Comment by aparnacoronasafe** [comment]
Yes. BP can be zero.
