### ISSUE TITLE
'make load-dummy-data' is not working as expected.

### ISSUE THREAD

**Issue by shyamprakash123** [coronasafe/care#1833]
**Describe the bug**
When we load the dummy data into the backend it produces an error.

**To Reproduce**
1. make up
2. make load-dummy-data
3. See error

**Screenshots**
![Screenshot 2024-01-18 072954](https://github.com/coronasafe/care/assets/106866225/0784eaf7-25bf-46b5-a839-33321f427def)

![Screenshot 2024-01-18 074619](https://github.com/coronasafe/care/assets/106866225/55c34e46-4745-4b6d-9a16-201e1b69d5c4)

![Screenshot 2024-01-18 150512](https://github.com/coronasafe/care/assets/106866225/b10273dc-c7f1-493a-a0f4-ac70722f009e)

**Comment by rithviknishad** [comment]
@shyamprakash123
