### ISSUE TITLE
Generated discharge summary file names ending with `.pdf.pdf`

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care#1961]
**Describe the bug**
Generated discharge summary file names ending with `.pdf.pdf`

**To Reproduce**
1. Go to a live patient and discharge them or open a discharged patient.
2. See file name of the discharge summary in consultation files

**Expected behavior**
Should end with `.pdf` instead

**Screenshots**
<img width="1160" alt="image" src="https://github.com/coronasafe/care/assets/25143503/1e8cb550-cb4b-493e-8168-793b8ea36d70">

**Comment by krassowska** [comment]
I would like to try and resolve this issue.

**Comment by ShailRT** [comment]
Can I work on this?

**Comment by krassowska** [comment]
It looks like it might have been introduced by the recent pull request: https://github.com/coronasafe/care_fe/pull/7305.

The `renderFileUpload` method [new includes](https://github.com/coronasafe/care_fe/blob/f39ce8344e7087cfe3288fcabc761cd671221df0/src/Components/Patient/FileUpload.tsx#L579-L580) the following:

```tsx
  <span className="font-semibold leading-relaxed">
    File Name:{" "}
  </span>{" "}
  {item.name}
  {item.extension}
```

but previously it was:

```tsx
 <div>
  <span className="font-semibold leading-relaxed">
    File Name:{" "}
  </span>{" "}
  {item.name}
</div>
```


but name as stored in `FileUpload.name` already has `.pdf` extension, added in:

https://github.com/coronasafe/care/blob/8616f5c956f0ee8f252ea5f0581bb1fd2dff986f/care/facility/utils/reports/discharge_summary.py#L180-L185

Would it be better to change it on back-end or frond-end? My thinking is that it may be better fixing it on front-end, as on back-end it was working okay, it communicates with S3 so I'm not sure what implication would be for changing file name pattern. Front-end uses files taken from S3 and the code adding second ".pdf" extension is a new addition so changing it should not cause much issues for the whole system.

I saw that there were no tests for this part of code. Would you accept a pull request adding a test? I may have time over the weekend to add it.

**Comment by rithviknishad** [comment]
@krassowska 

FileUpload's name wouldn't contain the extension in the `name` column. This field is more like a label than a file name on disk. The `internal_name` column is the file name on the disk and contains the proper extension. Only auto-generated discharge summary files have `.pdf` suffixed in the `name` column. Rest all does not. So this needs to be fixed in the backend. 

cc: @sainak 

<img width="1548" alt="image" src="https://github.com/coronasafe/care/assets/25143503/c1d406b8-7c32-483c-9931-44c79025d569">



Yes, you can add tests too.
