### ISSUE TITLE
Issue with patient export for last consultation but re-registered without consultation filed

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care#1998]
**Describe the bug**
When a patient is registered again, but no consultation is filed, the patient CSV export contains that patient but consultation-related fields consist of fields related to previous consultation.

**To Reproduce**
1. Register an existing patient to a facility without filing a consultation
2. Export the patient list that covers this patient
3. See error

**Screenshots**
@nihal467

**Comment by nihal467** [comment]
![image](https://github.com/coronasafe/care/assets/57055998/34915495-f720-4936-adbe-02b01e2816f6)

[export_2024-03-21_13_10_53.csv](https://github.com/coronasafe/care/files/14691721/export_2024-03-21_13_10_53.csv)

**Comment by rithviknishad** [comment]
Decided to ignore patients whose last consultation has a discharge date. 

cc: @gigincg
