### ISSUE TITLE
Creating a super user without creating a district results in an error

### ISSUE THREAD

**Issue by shivankacker** [coronasafe/care#2004]
**Describe the bug**
Setup project, create a super user. It results in an error that wont resolve until there is a district record.

**Expected behavior**
Either no district should be assigned by default to the super user or a warning should appear telling the dev to load dummy data first

**Screenshots**
![image](https://github.com/coronasafe/care/assets/23238460/789f2e71-1dea-4865-8489-b2b038ca7bc8)

**Comment by prabs222** [comment]
Hey @skks1212
Can you assign it to me?

**Comment by prabs222** [comment]
Hey @skks1212
Can you assign it to me?

**Comment by shivankacker** [comment]
> Hey @skks1212
> Can you assign it to me?

@prabs222 this has already been taken up and a fix will be deployed soon.

@sainak can you please assign the issue to me so there is no confusion?
