### ISSUE TITLE
Sending a notification to patient via SMS about their appointments

### ISSUE THREAD

**Issue by rash-27** [coronasafe/care#2037]
**Is your feature request related to a problem? Please describe.**
@coronasafe/care-backend-maintainers Currently, we are using this sendSMS function, which uses the Amazon SNS service to send OTPs to patients. Can we also use the same function to notify a patient about the appointment via SMS ?
![Screenshot from 2024-03-31 04-53-35](https://github.com/coronasafe/care/assets/146672184/aefb5679-0956-40bd-adb6-a707d866087d)

**Comment by BlessedRice2004** [comment]
@rash-27 If this is still a relevant issue, may I work on this one?

**Comment by Rustix69** [comment]
I would like work on this, if that's okay.

**Comment by rithviknishad** [comment]
Appointments is not yet present in care and is a work in progress. We can consider building this out once Appointments are live.
