### ISSUE TITLE
Add Admin Panel Filters

### ISSUE THREAD

**Issue by vigneshhari** [coronasafe/care#210]
Add filters for district/local body/state to all models that contain those fields. Add searchable foreign key fields as well, since there are going to be many objects in the foreign key selection dropdown

**Comment by sandeepsajan0** [comment]
I am working on it.

**Comment by vigneshhari** [comment]
Since this is a production Issue, Please try to solve the issue by tonight itself.

**Comment by sandeepsajan0** [comment]
https://github.com/coronasafe/care/pull/213#discussion_r401542513 need to add filters for every models there like Facility staff, Inventory, etc?

**Comment by sandeepsajan0** [comment]
I think it is not completed yet?
