### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by anroopak** [coronasafe/care#211]
There are quite a lot of tests which are failing because we moved from pytest to UnitTests. 
Also there were a lot of changes in the application by the time we ported. 
Need someone to work on this.

**Comment by afzalIbnSH** [comment]
I think Abhyudai is already working on this. @abhiabhi94 Can you push your PR against this issue. The earlier you can the merrier.

**Comment by abhiabhi94** [comment]
Till the time, all texts are fixed, I would suggest to run only `pytest` tests. We can add some sort of regex when running tests that does not run file ending with `_api.py`. There is a file `test_models.py` inside `care/users/` while also need not be run currently. The above argument is based upon the assumption that none else apart from me has added tests based on `django` `unittest`.

**Comment by abhiabhi94** [comment]
I think this can be closed now.
