### ISSUE TITLE
max_length should be 15 when using PhoneNumberValidator 

### ISSUE THREAD

**Issue by V01D0** [coronasafe/care#2126]
In care/facility/models/asset.py, the max_length for phone numbers is 14. According to ITU-T E. 164, the max_length for phone numbers should be 15.

[asset.py (Line 103)](https://github.com/coronasafe/care/blob/cf6902ba60491d3849754c603745072c1b8394d2/care/facility/models/asset.py#L103)

[Reference 1](https://www.oreilly.com/library/view/regular-expressions-cookbook/9781449327453/ch04s03.html)

[Reference 2](https://stackoverflow.com/a/3350566)

**Comment by sainak** [comment]
closed in  #2138
