### ISSUE TITLE
Dev container runs `make up` every time you connect to it

### ISSUE THREAD

**Issue by shivankacker** [coronasafe/care#2142]
**Describe the bug**
`Make up` runs every time I connect to a codespace

**To Reproduce**
Create a codespace on develop.
Disconnect and connect again 

**Expected behavior**
Make up should run after create not after attach

**Comment by sainak** [comment]
https://containers.dev/implementors/json_reference/#lifecycle-scripts

running `make up` in `postStartCommand` would be better as that would ensure that the dev environment is running when the container starts
