### ISSUE TITLE
Add a global 20 seconds timeout to middleware requests

### ISSUE THREAD

**Issue by sainak** [coronasafe/care#2237]
https://github.com/ohcnetwork/care/blob/4f6296ac76ceedc0a8c07a83689a3c7fcfe9f2a0/care/utils/assetintegration/base.py#L35-L61

add a settings variable to set timeout for middleware requests
use 20 seconds as defaults

**Comment by praffq** [comment]
@sainak I'll like to work on this issue

**Comment by sainak** [comment]
completed in https://github.com/ohcnetwork/care/pull/2434
