### ISSUE TITLE
Optimize the N+1 query occurrence in the `/api/v1/facility/` endpoint to improve performance and reduce database load.

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care#2256]
### Feature Request

**Description**
Optimize the N+1 query occurrence in the `/api/v1/facility/` endpoint to improve performance and reduce database load.

- **ViewSet File**: `care/facility/api/viewsets/facility.py`
- **Serializer**: `care/facility/api/serializers/facility.py`

**Suggested Solution**
To address the N+1 query problem, use Django's `select_related` and `prefetch_related` methods:
1. **Use `select_related`**: For single-valued relationships (e.g., foreign keys, one-to-one relationships) to perform SQL joins and fetch related objects in a single query.
2. **Use `prefetch_related`**: For multi-valued relationships (e.g., many-to-many, reverse foreign keys) to fetch related objects in separate queries and join them in Python.

**Additional Context**
Optimizing these queries should enhance the endpoint's performance, reduce the number of database queries, and lower the overall load on the database.

**Comment by rithviknishad** [comment]
Closing as duplicate and new solution proposed in https://github.com/ohcnetwork/care/issues/2481
