### ISSUE TITLE
S3 Bucket Health Check

### ISSUE THREAD

**Issue by tellmeY18** [coronasafe/care#2282]
**Description:**
The health of S3 buckets (read/write access) is not currently being monitored. When there is downtime for the S3 buckets due to billing issues or other reasons, it is only identified when users are unable to access image files.

**Suggested Solution:**
Implementing a built-in health check for S3-compatible buckets within the system itself appears to be a viable solution. This addition could include a read and write function that acts as a probe to the bucket and runs in the background at specified intervals.

**Additional Context:**
Making the bucket status available at the /health endpoint will ensure that current uptime monitoring systems, which check for API health, can detect and report downtime without requiring additional configurations.

**Comment by bodhish** [comment]
Is this really required? 🤔

**Comment by sainak** [comment]
It's very less likely that something is wrong with s3 in case of bucket issues, so we have decided not to move forward with this.
