### ISSUE TITLE
Explicitly Mention ACL for Public Uploads

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care#2335]
Currently Facility Image Uploads are pointed to a Public S3 Bucket on AWS Deployments, for S3 Compatible Providers, like Digital Ocean, the ACL Needs to be explicitly specified when uploading the file. 

Explicitly mention Public ACL for Facility Cover Image Uplaods

We've seen this happen on Digital Ocean Spaces. Refer [docs](https://docs.digitalocean.com/reference/api/spaces-api/#upload-an-object-put)

**Comment by amjithtitus09** [comment]
I would like to work on this issue

**Comment by gigincg** [comment]
@amjithtitus09 Please raise a Draft PR when you start working on it.
