### ISSUE TITLE
Add a contact number field for facility.

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care#24]
This is a requirment that came from `Ambulance Network`

**Comment by abinmn** [comment]
Can I take up the issue?

**Comment by bodhish** [comment]
@abinmn can you check with @vigneshhari

**Comment by vigneshhari** [comment]
@abinmn Continue and add , make sure you add the migrations as well

**Comment by abinmn** [comment]
Is this a mandatory field?

**Comment by vigneshhari** [comment]
@bodhish

**Comment by bodhish** [comment]
We are yet to go live. So it's safe to seed 1234567890
