### ISSUE TITLE
Password Reset Allows Any Username

### ISSUE THREAD

**Issue by AdityaJ2305** [coronasafe/care#2409]
#### Description

The password reset feature allows a reset request for any username, including invalid ones, without checking if the username exists.
<img width="1440" alt="Screenshot 2024-08-28 at 1 20 32 PM" src="https://github.com/user-attachments/assets/0285375b-ffdf-4797-974e-44d3ac635b78">
it is returning res.ok = true for every username 
#### Steps to Reproduce

1. Go to the password reset page.
2. Enter a random or invalid username.
3. Submit the request and see that a success message is shown.

#### Expected Behavior

- The system should validate if the username exists and return an error if it does not.

#### Actual Behavior

- Success message is shown for any username entered, regardless of its validity.

#### Proposed Fix

- Validate username existence properly before processing the request.

---

**Comment by inv-amalusudhakaran** [comment]
I would like to work on this issue

**Comment by bodhish** [comment]
It's intentional; As per OWASP we should do that.

```
Return a consistent message for both existent and non-existent accounts.

```

https://cheatsheetseries.owasp.org/cheatsheets/Forgot_Password_Cheat_Sheet.html

**Comment by bodhish** [comment]
@rithviknishad 👆note
