### ISSUE TITLE
Add field `prescribed_by_doctor` for Prescriptions

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care#2426]
Related to https://github.com/ohcnetwork/care_fe/issues/8492

- If the create prescription request's user is a doctor with home facility access, use that as the value for `prescribed_by_doctor`, otherwise this attribute should be provided by the client.

**Comment by Rajasimhareddybolla** [comment]
Hey @rithviknishad, I want to work on this issue. Can I add the prescribed_by_doctor attribute to the Prescription model?

**Comment by himanshu-sharmav** [comment]
Hi @rithviknishad @sainak I would like to work on this issue.

**Comment by Jeffrin2005** [comment]
@rithviknishad I would like to work on this. Could you please assign it to me?

**Comment by rithviknishad** [comment]
Will reopen once https://github.com/ohcnetwork/care_fe/issues/8492 is ready to be picked up.
