### ISSUE TITLE
Header and footer spacing in Discharge summary

### ISSUE THREAD

**Issue by Zeshanxviii** [coronasafe/care#2430]
**Is your feature request related to a problem? Please describe.**
The format of **Discharge** **Summary**  in CARE needs to be improved

-  Discharge  Summary

The pages have no spacing at the header and footer.
The page breaks between sentences

**Describe the solution you'd like**

- [ ]  Add spacing at the head and the foot of page
- [ ]  Do not allow page to break sentences.

Related Issue [care_fe issue #8430](https://github.com/ohcnetwork/care_fe/issues/8430#issue-2488504935l)

**Describe alternatives you've considered**

**Additional context**

**Comment by praffq** [comment]
@Zeshanxviii  is this issue relevant to backend now ? 🤔  if yes , can you explain what need to be updated here

**Comment by Zeshanxviii** [comment]
> @Zeshanxviii is this issue relevant to backend now ? 🤔 if yes , can you explain what need to be updated here

https://github.com/ohcnetwork/care/blob/develop/care/templates/reports/patient_discharge_summary_pdf_template.typ

Just, you have to update layout

**Comment by praffq** [comment]
This has recently being updated. Have you rechecked it?
