### ISSUE TITLE
Add a timeout for open id authentication

### ISSUE THREAD

**Issue by sainak** [coronasafe/care#2440]
https://github.com/ohcnetwork/care/blob/4f6296ac76ceedc0a8c07a83689a3c7fcfe9f2a0/config/authentication.py#L80
https://github.com/ohcnetwork/care/blob/4f6296ac76ceedc0a8c07a83689a3c7fcfe9f2a0/config/authentication.py#L201

**Comment by pakhare** [comment]
@sainak Can you assign this to me?

**Comment by Dishaswamy** [comment]
@sainak can u assign this to me ? this can be an issue with invalid url so adding a time out can easily fix it

**Comment by sainak** [comment]
completed in https://github.com/ohcnetwork/care/pull/2483
