### ISSUE TITLE
Add an option to list patients registered via tele medicine

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care#246]
There should be an option to list all the patients registered / consulted via tele medicine for district admin

**Comment by shalicemoideen** [comment]
I would like to know about how we can identify the tele medicine patient. I think currently we have  `PatientRegistration`  and `PatientTeleConsultation` where patient foreign key mapped.

I am new to this project and I don't have much idea about the total work-flow, please correct me if am wrong
