### ISSUE TITLE
Create tables for managing Inventory in a facility. 

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care#247]
Create tables for managing Inventory

Faculty should have a public page where they could list the current inventory and required inventory.

People should be able to see the requirements on a public page and contribute if required 
(this would be super import for make shift hospitals)

**Comment by anroopak** [comment]
@bodhish Do we have values which can be added in the inventory? Also the list may vary and may not be exhaustive. 

Tables have been already added. Proposed APIs

/inventory_item/ CRUD
Inventory item will be equivalent to a particular item, eg Bedsheet. 
```
{
   "name",
   "description",
   "unit",
   "minimum_stock"
}
```

/facility/id/inventory/ 
Will use the ID of the above API and put in the quantities
Only PATCH API will be provided. API request body can be an array of these items, items shall be upserted (updated or inserted)
```
{
    "inventory_item": ID from the above API,
    "current_quantity": 
    "required_quantity": 
}
```

**Comment by bodhish** [comment]
https://model.coronasafe.network/centralised-facilities/inventory-supplies

**Comment by vigneshhari** [comment]
API's for managing inventory is implemented
