### ISSUE TITLE
Cache counts on /api/v1/facility/ route 

### ISSUE THREAD

**Issue by sainak** [coronasafe/care#2481]
/api/v1/facility/  is causing n+1 quires due to count of beds and patients,
to optimize this, instead store the count in redis 
tasks:
- store count of active patients and beds in redis
- invalidate count when the data changes
- come up with an optimized way or storing count of multiple facilities if it doesnt exists
- make the helper funcions abstract so that they can be used with other fields/models

**Comment by BlessedRice2004** [comment]
@sainak May I work on this issue?

**Comment by gigincg** [comment]
Additional Context, the issue is to use the approach in https://github.com/ohcnetwork/care/pull/1349 but abstract out the helper functions

**Comment by ANIR1604** [comment]
I had solved the issue. I would like work on this, if that's okay.
