### ISSUE TITLE
Add Validation for Insurance input fields in patient registration form

### ISSUE THREAD

**Issue by syedfardeenjeelani** [coronasafe/care#2507]
Refer backend changes reuqired mentioned here: https://github.com/ohcnetwork/care_fe/issues/8672

**Comment by Waheedsys** [comment]
Hey, would it be okay if I worked on this issue?

**Comment by himanshu-sharmav** [comment]
Hi @rithviknishad  , would like to work on this issue.

**Comment by AmanSingh-tech** [comment]
hey @rithviknishad , i would like to work on this issue

**Comment by AmanSingh-tech** [comment]
Thank you @rithviknishad

**Comment by praffq** [comment]
@rithviknishad  can I pick this up?  It's been idle for more than 2 weeks

**Comment by AmanSingh-tech** [comment]
Yes you can

**Comment by gigincg** [comment]
I don't think this is relevant anymore. We don't have a database of insurers to begin with. Assigning it to @khavinshankar to review and close based on how the HCX implementation works

**Comment by khavinshankar** [comment]
This is not relevant anymore, the validations are already implemented in the front end for now. These fields are subject to change when NHCX integrations are finalized.
