### ISSUE TITLE
Update `delete_old_notifications` task to allow configurable time period with default of 30 days

### ISSUE THREAD

**Issue by sainak** [coronasafe/care#2528]
ref: https://github.com/ohcnetwork/care/pull/1328

- [ ] Add settings variable `NOTIFICATION_RETENTION_DAYS` for delete time period
- [ ] Update tests

**Comment by arilloid** [comment]
Hello @sainak ,

I would like to work on this issue!

**Comment by ghost** [comment]
Hey @arilloid , are you working on this issue ?

**Comment by arilloid** [comment]
Hello @Alokih , 
Yes, I have finished implementing the change, I am trying to test it right now, but have troubles with the dev environment

**Comment by ghost** [comment]
Okay @arilloid 👍
