### ISSUE TITLE
Add Input Validation for /patient API Search Parameters

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care#2580]
Update the `/patient` API to incorporate input validation on search parameters, ensuring user inputs conform to defined limits. 

For instance, the `name` field currently accepts up to 200 characters, but the search functionality inadvertently allows more. 

We should also verify the same for all other supported fields. 

Also the api should be `/patients` instead of `/patient` right? 🤔

**Comment by praffq** [comment]
Can I pick this issue?

**Comment by himanshu-sharmav** [comment]
Hi, @bodhish @sainak  I would like to work on this issue.
