### ISSUE TITLE
Disallow numeric values in patient names

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care#2602]
Add backend validations too for issue mentioned in: https://github.com/ohcnetwork/care_fe/issues/9143

**Comment by notBigO** [comment]
Hello! i'd love to take this up

**Comment by mdaatifayman786** [comment]
hey @notBigO i want to work on this can you assign me

**Comment by rithviknishad** [comment]
Closing as per https://github.com/ohcnetwork/care_fe/issues/9143#issuecomment-2491409154
