### ISSUE TITLE
icmr_sample route is broken

### ISSUE THREAD

**Issue by yash-learner** [coronasafe/care#2615]
**Describe the bug**
Clicking the `ICMR Specimen Referral Form` button from a sample page takes to patient test sample page (`patient/.../test_sample/.../icmr_sample`) which results in internal server error

**To Reproduce**
1. Click `Sample Test` tab in `side bar`
2. Click on `sample details` for any one of the sample.
3. Click on `ICMR Specimen Referral Form`

**Expected behavior**
The route should be handled if it is still in use otherwise it need to be handled accordingly. If this is not actively used and gets revamped with new upcoming [Lab management module](https://docs.ohc.network/docs/care/CEP/Draft/labs) I think we can ignore this.

**Additional context**

Sentry Issue: [CARE-F9X](https://coronasafe-network.sentry.io/issues/5735753117/?referrer=github_integration)

http://careapi.ohc.network/api/v1/patient/c31e9b1f-0edc-4b4e-9b26-4ad9dfcbd698/test_sample/d5fbfd97-b225-48ef-aff6-914f73b75566/icmr_sample/

```
TypeError: 'RelatedManager' object is not iterable
(12 additional frame(s) were not displayed)
...
  File "care/facility/api/viewsets/patient_sample.py", line 107, in icmr_sample
    return Response(data=PatientICMRSerializer(patient).data)
  File "care/facility/models/patient_icmr.py", line 164, in symptoms
    for symptom in self.consultation.symptoms:
```

**Comment by BlessedRice2004** [comment]
Hi @yash-learner,
May I take on this issue?

**Comment by JohnLu2004** [comment]
Thank you. I won't let you guys down!

**Comment by yash-learner** [comment]
@JohnLu2004 Sorry for inconvenience 

As we discussed on Slack this route will be going away soon and with no active users using it. I believe it's not worth fixing it, will close the issue. Please pick a new one.

**Comment by yash-learner** [comment]
@JohnLu2004 Sorry for inconvenience 

As we discussed on Slack this route will be going away soon and with no active users using it. I believe it's not worth fixing it, will close the issue. Please pick a new one.
