### ISSUE TITLE
listAssetBedPresets and ListBedPresets mismatch

### ISSUE THREAD

**Issue by Jacobjeevan** [coronasafe/care#2619]
**Describe the bug**
Navigate to the Dev camera on Care, and check the preset options available on the feed page vs ones on the camera configuration page.

`/api/v1/assetbed/{assetbed_id}/camera_presets/` called in Configure Page(`AssetBedCameraPresetViewSet`)
`/api/v1/bed/{bed_id}/camera_presets/` called in Feed Tab(`CameraPresetViewSet`)

![Image](https://github.com/user-attachments/assets/e322e5da-ad04-4625-9fa5-98abf8a0f13c)

![Image](https://github.com/user-attachments/assets/28048c79-f63d-4616-8d2d-72b506a06f20)

**To Reproduce**
1. Go to https://care.ohc.network
2. Login with devdistrictadmin credentials
3. Navigate to Patient named 'Gigin'
4. Click on Feed Tab (alternatively, direct link to the feed page: https://care.ohc.network/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/edfe0bd6-0f50-4a4c-8cd0-2d4ad0e9cea1/feed)
5. Compare Bed Presets to ones under 'Bed 1' in Camera Configuration Page (click on the information icon and then 'Configure Camera')

**Expected behavior**
Bed Presets in the Feed tab should be the same as Bed Presets for corresponding Bed in the camera configuration page.

**Comment by praffq** [comment]
@Jacobjeevan  is this issue still valid? I can see the related fe issue is closed.

**Comment by Jacobjeevan** [comment]
> [@Jacobjeevan](https://github.com/Jacobjeevan) is this issue still valid? I can see the related fe issue is closed.

@DraKen0009 Still valid.

**Comment by praffq** [comment]
Alright. can you assign this to me , I'll try to get it fixed. Also I'm assuming this is not  priority issue and can be fixed by the weekend

**Comment by Jacobjeevan** [comment]
> Alright. can you assign this to me , I'll try to get it fixed. Also I'm assuming this is not priority issue and can be fixed by the weekend

Yea, that's fine. I don't have perms, pinging @sainak

**Comment by praffq** [comment]
Alright. Thanks

**Comment by praffq** [comment]
@Jacobjeevan @sainak  raised a PR for the issue , please review
