### ISSUE TITLE
Use UserAssignedSerializer for assigned_to_object

### ISSUE THREAD

**Issue by Rishith25** [coronasafe/care#2623]
### Description:
The `UserBaseMinimum` serializer currently does not include the `alt_phone_number` field, which is necessary for user data which is necessary in patient details page for volunteer . This missing field affects the ability to store and retrieve emergency contact details when using this serializer.

**Comment by Rishith25** [comment]
@Jacobjeevan @nihal467 Can you please assign it to me.

**Comment by ashwinpraveengo** [comment]
@rithviknishad  Can u please assign this issue to me?
