### ISSUE TITLE
Backend for Auto-scroll Issue and Total Count Card for Staff Capacity Pagination in facility details page

### ISSUE THREAD

**Issue by shauryag2002** [coronasafe/care#2628]
**Bug Description:**  
Auto-scroll behavior and incorrect total count display for staff capacity pagination in the facility details page.  

**Steps to Reproduce:**  
1. Go to the facility details page.  
2. Add or update staff capacity.  
3. Observe auto-scroll behavior.  
4. Check the total capacity card for incorrect count (shows current page only).  

**Expected Behavior:**  
- Auto-scroll should stop at the staff capacity section instead of the page's top.  
- Total capacity card should display the total staff capacity across all pages.  

**Screenshots/Recordings:** 

https://github.com/user-attachments/assets/1b04ecb1-ef59-4638-a177-87a36a463853

**Additional Context:**  
Fix reference Frontend: [[Issue #9122](https://github.com/ohcnetwork/care_fe/issues/9122)]
Fix reference Frontend Pull Request: [[PR #9275](https://github.com/ohcnetwork/care_fe/pull/9275)]

**Comment by bodhish** [comment]
Closing in favor of https://github.com/ohcnetwork/care_fe/pull/9436
