### ISSUE TITLE
Switch to minio from localstack in local dev

### ISSUE THREAD

**Issue by vigneshhari** [coronasafe/care#2634]
Locastack is a very heavy tool and unreliable at times and most features are blocked behind a paywall, switch to using [minIO](https://github.com/minio/minio)

**Comment by ANIR1604** [comment]
I had solved the issue. I would like work on this, if that's okay.

**Comment by gigincg** [comment]
@ANIR1604 Can you elaborate on "I had solved the issue"

**Comment by ANIR1604** [comment]
I will at first stop the localstack and install miniIo. Then We have to update the application config by replacing localstack s3 endpoints and run the aws with new credentials and then migrate the data.

**Comment by gigincg** [comment]
@ANIR1604 I don't think there's any migration required here, since localstack is only used for local dev environment

**Comment by amjithtitus09** [comment]
@ANIR1604 Hey, I've attempted this and linked the PR

@vigneshhari Have linked a PR, please review. Would like to add that minIO doesn't seem to support "public-read" ACL set during upload, hence 'facility-bucket' is initialized as public.

cc: @gigincg
