### ISSUE TITLE
Documentation Update And Manage.py To Ease Superuser creation

### ISSUE THREAD

**Issue by anuragkumart16** [coronasafe/care#2643]
**Is your feature request related to a problem? Please describe.**

After setting up the development server and headed towards creating superuser, I ran the following command 

`python manage.py runserver`

I recieved : 

`Couldn't import Django. Are you sure it's installed and 
available on your PYTHONPATH environment variable? Did you 
forget to activate a virtual environment?`

**Inorder to ease The process of Installation for First-time-contributers, following should be done:**

- The Documentation should be updated to tell about how to get in docker container and then create superuser.
- The Message in manage.py should be updated to say that there is a need to get in docker container and then create a superuser.

**Additional context**

![Image](https://github.com/user-attachments/assets/a5cf4987-0fe1-4047-bcd9-21e201c8c72e)

**Comment by rithviknishad** [comment]
The backend docs does contain information about loading dummy data which will create the super user for you.

To run any django commands, you'll have to enter into the docker container's shell and run the command.

You might have mixed up things by reading manual setup docs with docker based setups.

Django app in itself need not be aware of whether it is run using docker or not.
