### ISSUE TITLE
Remove summarization tasks and apis

### ISSUE THREAD

**Issue by sainak** [coronasafe/care#2651]
https://github.com/ohcnetwork/care/blob/dc578c7cbce5b66cf5121cbbc9fbd5e44c1d0133/care/facility/tasks/__init__.py#L26-L55

Remove the following stuff for each of the above tasks:
- task definition
- api endpoints
- serializers and views
- settings and mentions in docs

**Comment by areebahmeddd** [comment]
Hi, can i be assigned to this issue? :)
