### ISSUE TITLE
Create a new make target to remove volumes along with the docker containers

### ISSUE THREAD

**Issue by sainak** [coronasafe/care#2657]
https://github.com/ohcnetwork/care/blob/7d3d95864354ac6e46036dfae5461dcebcaa0886/Makefile#L28-L30

Add a new make target named `teardown` that runs the above command with the `-v` flag, this should remove the volumes along with the containers

Add docs for this behavior

**Comment by saltykheera** [comment]
vishal kumar

**Comment by areebahmeddd** [comment]
@saltykheera Hey, this seems like a quick fix? Are you still on it?

**Comment by saltykheera** [comment]
yes fixed it making the pr tomorrow positively
