### ISSUE TITLE
Add an option to choose latitude and longitude

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care#27]

**Comment by anroopak-ab** [comment]
I can take this up.

**Comment by 9746264571** [comment]
i can also work on this

**Comment by anroopak-ab** [comment]
@bodhish Can you add more info to which model this change is required?

**Comment by vigneshhari** [comment]
Facility requires a latitude and longitude

**Comment by afzalIbnSH** [comment]
I'm already doing it.

**Comment by vigneshhari** [comment]
please submit a PR ASAP @afzalIbnSH

**Comment by shanavas786** [comment]
@afzalIbnSH hope your approach leverages browser's location API

**Comment by 9746264571** [comment]
@afzalIbnSH any updates on the PR?

**Comment by vigneshhari** [comment]
He has submitted the PR for adding the feature #62 , @shanavas786 there is no need to use the browsers inbuilt location API, 1) It can be very wildly incorrect 2) This is just the backend part, the front end is written as a separate app on REACT, so you can have a discussion with that team to see various ways to select the location from the device.

**Comment by vigneshhari** [comment]
The feature is added, closing this issue
