### ISSUE TITLE
Patient data should be searchable and uniquely identifiable

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care#276]
The patient data be uniquely identifiable.
The search should work with number, name or any other field in patient data without exposing medical records. 

Flow will be, 
When creating a new patient, we should give an option to select from a list of patients with matching details. Allow patient creation only if it's unique

**Comment by tomahawk-pilot** [comment]
not possible. since we are encrypting everything. search is not possible.

**Comment by tomahawk-pilot** [comment]
maybe @anroopak or @vigneshhari has some alternatives for that

**Comment by vigneshhari** [comment]
We are building something else for this.

**Comment by tomahawk-pilot** [comment]
ok da. nothing that exposes to another facility about patient in another facility
