### ISSUE TITLE
In the "Add Details of Covid Suspect / Patient" Form >> The Checkboxes for "Any medical history? (Diabetes, Heart Disease, HyperTension, Kidney Diseases) must be unchecked/reset by default.

### ISSUE THREAD

**Issue by roshinraj007** [coronasafe/care#285]
In the "Add Details of Covid Suspect / Patient" Form >> The Checkboxes for "Any medical history? (Diabetes, Heart Disease, HyperTension, Kidney Diseases) must be unchecked/reset by default.

Currently, these checkbox remains 'Checked' based on the previous record submission.

Expected : By default, these checkboxes must be unchecked - "Any medical history? (Diabetes, Heart Disease, HyperTension, Kidney Diseases)

**Comment by vigneshhari** [comment]
It should remain checked right?  if we are editing a patient history?
