### ISSUE TITLE
unnecessary tests?

### ISSUE THREAD

**Issue by gabru-md** [coronasafe/care#29]
[test_views.py](https://github.com/coronasafe/care/blob/master/care/users/tests/test_views.py) is testing classes which are commented out in the [main file](https://github.com/coronasafe/care/blob/master/care/users/views.py#L31).
```python
from care.users.views import UserRedirectView, UserUpdateView
```
the following classes have been commented out in the project.

should the tests be removed as well for now?

**Comment by vigneshhari** [comment]
Yeah go ahead and remove them as well, the tests came standard with cookiecutter Django, and are no longer required

**Comment by gabru-md** [comment]
cool
