### ISSUE TITLE
Confirmation missing while signing up as hospital admin

### ISSUE THREAD

**Issue by JikkuJose** [coronasafe/care#296]
- [ ] No email confirmation on signup
- [ ] No message confirming sign-up process

**Comment by tomahawk-pilot** [comment]
We plan to remove the signup entirely and let District level admin to register user and share credentials to avoid duplication of users

**Comment by vigneshhari** [comment]
The Email Confirmation is active as a separate issue , that involves resetting the password with the email once the password is lost, I will close this issue as this seems like duplicates
