### ISSUE TITLE
Form validation message not visible

### ISSUE THREAD

**Issue by JikkuJose** [coronasafe/care#297]
While adding a patient a validation (like Aadhaar format error) prevents the form from submitting without an obvious hint like a toast/popup message. Especially confusing while trying to enter data from a mobile device where the validation message is much above in the page and cannot be seen.

**Comment by vigneshhari** [comment]
This seems like a front end issue rather than a backend one, Shall i move it to the front end repo for you ?

**Comment by JikkuJose** [comment]
Yes, please. I wasn't sure where the issues were tracked. Looks like Jira is used?

**Comment by vigneshhari** [comment]
Jira is used in addition to the GitHub issues, to my knowledge, 
For Front End You can create issues here: https://github.com/coronasafe/care_fe 
Closing this issue now.

**Comment by vigneshhari** [comment]
Issue can now be viewed at https://github.com/coronasafe/care_fe/issues/239
