### ISSUE TITLE
Ambulance API doesn't work for remove driver action

### ISSUE THREAD

**Issue by abhiabhi94** [coronasafe/care#300]
The issue is similar to #299 and has similar reasons for this behaviour

**Comment by abhiabhi94** [comment]
Also as far as I can see here https://api.care.coronasafe.in/redoc/#operation/ambulance_remove_driver, the documentation doesn't mention anything about the `id` of the driver. Since there can be multiple drivers attached to one ambulance, how does the API know which driver to remove when no information about the driver's id is passed to it from the request?

**Comment by vigneshhari** [comment]
Currently, we have a neat implementation of adding and removing drivers and editing them from the Django admin panel, since we are not letting anyone edit or remove the drivers other than the superuser this kind covers our needs at the moment.

**Comment by vigneshhari** [comment]
You can close this issue and start a new issue for covering the whole ambulance driver's CRUD operations and implement it properly as well.

**Comment by tomahawk-pilot** [comment]
Decommissioned APi
