### ISSUE TITLE
add states_travelled info to the patient 

### ISSUE THREAD

**Issue by anroopak** [coronasafe/care#323]
- add following fields
  - `states_travelled` info to the patient model - similar to `countries_travelled`
  - `last_visited_country` - String
  - `last_visited_state` - State ID 
  - add `date_of_return_state` - date of return from the state visited. 

Links to #308. PRs should solve both.

**Comment by anroopak** [comment]
Who ever is picking this up, try to put this as a mixin and clean up the model

**Comment by abhiabhi94** [comment]
Should we use https://github.com/yourlabs/django-autocomplete-light for `states_travelled` or a text field is good enough? It would in keeping the database clean and help in any future analysis, if any.

**Comment by abhiabhi94** [comment]
what kind of cleaning etc do you want? I have added the field and made the traveled fields as `JSONField`?

**Comment by anroopak** [comment]
Not required now.
