### ISSUE TITLE
add uniqueness constraint for phone number and DOB

### ISSUE THREAD

**Issue by anroopak** [coronasafe/care#329]
Add a uniqueness constraint for Phone number and DOB in Patient model.

EDIT:
Uniqueness shall be applied together, ie Phone + DOB shall be unique for any patient. 

Possible corner cases are for twins, we will ignore that case for now.

**Comment by abhiabhi94** [comment]
do we expect all patients to have a separate phone number?
there can be families with none or at the most one phone number.

**Comment by abhiabhi94** [comment]
`phone_number` is an encrypted field inside the model `PatientRegistration`. As per the documentation of the fernet, exact lookup is not possible.
Reference link: https://django-fernet-fields.readthedocs.io/en/latest/#indexes-constraints-and-lookups
