### ISSUE TITLE
Needing occupancy percentage

### ISSUE THREAD

**Issue by snehil0802** [coronasafe/care#367]
https://data.coronasafe.network/dashboard/4 
This dashboard only gives the number of occupied and available. Kindly put the percentage occupied for each.

The Hospitals have to be color coded as Government hospitals and private hospitals.

Can there be an option of viewing the total occupancy based on the classification of Government hospitals and private hospitals.

**Comment by gigincg** [comment]
Added all requirements to the dashboards

**Comment by bodhish** [comment]
![IMG-20200430-WA0010](https://user-images.githubusercontent.com/14979190/80668164-c151bc00-8abe-11ea-89a3-239ca4fbd629.jpg)
