### ISSUE TITLE
Unavailable: api.care.coronasafe.in

### ISSUE THREAD

**Issue by VaibKS** [coronasafe/care#398]
I think you may already know about this, but still adding this in because I didn't see any discussion of this issue.

There is an SSL error with `https://api.care.coronasafe.in`.

Domain Mismatch probably?

![image](https://user-images.githubusercontent.com/6205961/85312636-b7ec3b00-b4d4-11ea-954f-1740f20415b6.png)

**Comment by tomahawk-pilot** [comment]
Hey @VaibKS we are not using this domain anymore. 
the staging API is https://careapi.coronasafe.in

**Comment by tomahawk-pilot** [comment]
https://careapi.coronasafe.in/redoc and https://careapi.coronasafe.in/swagger . api docs

**Comment by VaibKS** [comment]
The README specifies the older one. Needs to be updated.

**Comment by tomahawk-pilot** [comment]
will do @vigneshhari
