### ISSUE TITLE
Collect more details from facility.

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care#4]
- [x] Address
- [ ] Location - (this is important for the ambulance network)

**Comment by vigneshhari** [comment]
Specifically what do you mean be address ? just a text field ? how do we take Location ? lat long ?

**Comment by bodhish** [comment]
Add `text_field` address. Also add optional `lat long`. If they are unable to fill it, We can ask some volunteer to update those

**Comment by afzalSH** [comment]
I'll add the lat long
