### ISSUE TITLE
Create the Facility and Related Endpoint

### ISSUE THREAD

**Issue by vigneshhari** [coronasafe/care#40]
Create the Facility endpoint along with related models like Facility Capacity, Hospital Doctors and so on ..

**Comment by abinmn** [comment]
I'll take it up.

**Comment by abinmn** [comment]
Should I include routing details on a separate router file or in `api_router.py`?

**Comment by vigneshhari** [comment]
you can use the api_router, i don't know if the api_router is implemented properly thou, test it out and use that.

**Comment by vigneshhari** [comment]
The Facility Endpoint is now completed so closing this issue
