### ISSUE TITLE
Involve the "Shifting facility" in shifting process.

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care#400]
Please change the flow of shifting such that the "shifting facility" also has to take some positive steps to complete the shifting process.

What is happening now is that the receiving facility sometimes shifts patient cards without the knowledge of the shifting facility causing confusion.

**Comment by aparnacoronasafe** [comment]
@vigneshhari

**Comment by bodhish** [comment]
@vigneshhari @tomahawk-pilot is this resolved with the lock trasfer :thinking:

**Comment by vigneshhari** [comment]
This is solved.  Moving issue to solved
