### ISSUE TITLE
Make email optional for discharge email form

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care#403]
use the email of the user if email id is not specifed on the API. 
Also add the email to the sucess notification so that user knows to which email the repot is being sent.

**Comment by Ajuajmal** [comment]
I found that currently there is an option for adding user email from front end itself,

![Screenshot from 2020-06-30 21-14-20](https://user-images.githubusercontent.com/28041916/86149300-6ddd0800-bb19-11ea-8819-7d9a67c1a776.png)

For notifying the email address
I tried to pass response with email data in `discharge_summary` function from `PatientViewSet` and shown the data in the success notification.

![Screenshot from 2020-06-30 21-44-04](https://user-images.githubusercontent.com/28041916/86150368-f1e3bf80-bb1a-11ea-8059-3d404c0b4207.png)

![Screenshot from 2020-06-30 21-45-20](https://user-images.githubusercontent.com/28041916/86150466-0de76100-bb1b-11ea-9186-13933d806f1e.png)

If this one is fine for solving the issue, then I will make a pull request on this.

**Comment by vigneshhari** [comment]
@Ajuajmal sorry for the late response, this issue was already solved by the front end.
