### ISSUE TITLE
Patient Summarization APIs

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care#409]
Summarization of Total Patient Data grouped by Facility
NOTE: Summarization from Patient Data, NOT Triage or Capacity
{
facility_name,
district,
modified_date
total_patients_icu,
total_patients_ventilator,
total_patients_isolation,
total_patients_home_quarantine
today_patients_icu,
today_patients_ventilator,
today_patients_isolation,
today_patients_home_quarantine
}

**Comment by Ajuajmal** [comment]
I'm working on this.
