### ISSUE TITLE
Minor corrections on copy

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care#41]
# after sign up (faculty admin) 
- [ ] add Success Notification: You successfully logged in to the corona care network

- [ ] add the following title

The next step is to register your Hospital into the corona care network and enter details about total capacity of regular beds, ICU beds, and ventilators. 

Once you connect your hospital to the corona care network, You will be able to view hospital details using th view hospital button.

# create hospital form 

- [ ] rename labels on the form as follows
- Enter the name of your hospital 
- Pick your District
- Enter your emergency contact mobile number of your hospital
> change button text : Add Your Hospital Information

# capacity/add form
- [ ] Add the following above the buttons. 

1. Save and Add information about another bed type.
2. Save the entered information and submit to the network
3. Cancel 

- [ ] The Error message for duplicates should be changed to : The bed type you are trying to add is already been added to the hospital, Please pick a different bed type. 

- [ ] Rename the Buttons 
Save &  Enter more Information
Save & Submit
Cancel

# doctor form 
- []  change label to - Area of specialization

# Facility Home. 

Add all the actions to top right 
- Add a Update hospital information 
- Update Information on hospital bed 
- Update Information on Doctor availability

- [ ] Add a total count of bed and doctors at the top

**Comment by sprajosh** [comment]
Working on this

**Comment by justinjohnymathew** [comment]
I have updated all form labels

**Comment by sprajosh** [comment]
@justinjohnymathew I'll drop this?

**Comment by justinjohnymathew** [comment]
@sprajosh  can you work on updating faculty home.

**Comment by bodhish** [comment]
Guys any update?

**Comment by justinjohnymathew** [comment]
@bodhish  I have some confusions with the facility home

**Comment by bodhish** [comment]
@justinjohnymathew lets do a call on slack. (@bodhi in http://slack.coronasafe.in/)
