### ISSUE TITLE
Capture Patient Shifting Flow

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care#435]
As the number of cases are growing, the district administration wants a system to manage shifting.

- The facility should have an option to request shifting for a patient based on consultation. 
- All the shifting request created by the facility should be listed
- Facility should have an option to see incoming patients as seperate tab
- district admin should see and have an option to update shifting

## shifting
- direction of shift - UP / Down 
- orgin facility
- destination facility  (optional)
- emergency flag
- reason for shifiting (text)
- vehicle_of_preference (text) (optional)
- comments (optional)
- status [ pending, approved, rejected, final_destination_confirmed, awaiting_vechicle, completed ]

**Comment by vigneshhari** [comment]
added another status for final destination rejected, in which case the shifting facility has to reallocate the facility

**Comment by vigneshhari** [comment]
also, we will consider the body that does the shifting as a facility, it helps with access control if the situation gets worse we can have multiple shifting facilities that the facility can opt for, for now, we can register one per district and be done with it

**Comment by vigneshhari** [comment]
This feature was implemented, The scoping filters for the feature have also been implemented, Closing this issue.
