### ISSUE TITLE
All facilities should have option of "Covid Beds"

### ISSUE THREAD

**Issue by snehil0802** [coronasafe/care#446]
in the care.coronasafe.network facilities- another bed type option should be present regarding "Covid Beds" - occupied and available.

**Comment by vigneshhari** [comment]
Will add another bed type, Changes will be active over the weekend.

**Comment by vigneshhari** [comment]
@tomahawk-pilot the changes required are made in the backend, please create an issue for the same in the front end and close this issue.

**Comment by tomahawk-pilot** [comment]
https://github.com/coronasafe/care_fe/commit/c28fa9ac21797178ae16be9578188b800bbae9c8

**Comment by tomahawk-pilot** [comment]
@vigneshhari Done @snehil0802  this is done. Hence closing this issue
