### ISSUE TITLE
maps- visibility of roads (Hotspots.coronasafe)

### ISSUE THREAD

**Issue by snehil0802** [coronasafe/care#447]
At present the visibility of the internal roads, which appears to be the base layer of the maps is not visible once the local body is selected. It is needed to understand actual containment zones. If possible, the road structure underlying is visible, it would be of help. 
Also, is it possible to add a layer, where we can ourselves draw over the present layer of local bodies.

**Comment by vigneshhari** [comment]
@bodhish shift issue to hotspot maps.

**Comment by saanuregh** [comment]
@snehil0802
First of all, future issues related to hotspot map can be created here https://github.com/coronasafe/kerala-map

1. Visibility of internal roads has been improved
![image](https://user-images.githubusercontent.com/49483918/89019276-b109e100-d33a-11ea-955e-c94c7faa4c1f.png)

2. As for the drawing feature, I'm currently working on it. Any further discussion can be made here https://github.com/coronasafe/kerala-map/issues/13
