### ISSUE TITLE
Migrate telemedicine to care

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care#448]
- [x] allow volunteers to create patient records
- [x] add new user role `doctor`
- [x] consultaion should have an option to assign doctors.
- [x] there should be an option to list live doctors given a facility
- [x] add actions for patients
- [x] actions should set review time
- [x] patients should be sorted by review time.
- [x] add consultation type telemedicine
- [x] add a login for community pharmacy
- [x] Add list api for prescriptions

**Comment by bodhish** [comment]
Prescription 
- [ ] scheme [government_supply, donation, paid_by_patient]
- [ ] supplier - text
- [ ] status - [pending, initiated, completed, deferred]
- [ ] remarks

**Comment by vigneshhari** [comment]
Correction, the Patient model will have an option to assign a doctor,
