### ISSUE TITLE
API for Patient details form

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care#47]
Patient registration flow should capture details of of close contacts and family members.

**Comment by anroopak** [comment]
What is the definition of family members?
1. People staying in the same home
2. Emergency contacts?

**Comment by Kailaash-Balachandran** [comment]
@anroopak @bodhish Is anyone already on it?

**Comment by bodhish** [comment]
No, it's open

**Comment by biswaz** [comment]
I've added the patient details model. Need apis for CURD on these models.
Models are at `care.facility.models.patient_data`

While creating the serializers, use https://github.com/goinnn/django-multiselectfield#django-rest-framework

**Comment by NavenAllen** [comment]
Can I take this up?

**Comment by anroopak** [comment]
@biswaz `PatientTeleConsultation` should be related to `PatientRegistration` right?

**Comment by anroopak** [comment]
@biswaz @vigneshhari created a PR - made a few small model changes also.

**Comment by vigneshhari** [comment]
Merged The PR
