### ISSUE TITLE
Disable suggestion for input fields. 

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care#48]
On Mac OS, the suggestion model is stuck 🙄. 

![IMG_20200322_113952](https://user-images.githubusercontent.com/14979190/77243625-31546300-6c32-11ea-98f2-75c0c7f2107f.jpg)

**Comment by vigneshhari** [comment]
what all fields should not have the suggestions field ?

**Comment by vigneshhari** [comment]
@bodhish

**Comment by bodhish** [comment]
disable for all fields other than first name, last name, phone number
