### ISSUE TITLE
For patient plasma donation keys default values are not ideal

### ISSUE THREAD

**Issue by MalayaliRobz** [coronasafe/care#480]
If the patient is willing to donate blood we fill boolean keys, "will_donate_blood" and "fit_for_blood_donation" with true in patient update api.
And if the patient is not willing we fill these keys with false.

But by default when creating a patient "will_donate_blood" and "fit_for_blood_donation" are prefilled with false.
Which can get confusing when looking at the downloaded patient data. You will not be sure if this is something the patient said or is this is default prefilled value.

**Having these key values as empty by default would help in differentiating if the patient has explicitly said yes or no to blood donation.**

**Comment by vigneshhari** [comment]
Corrected with an extra migration. closing this issue for now.
