### ISSUE TITLE
Better Permission Management

### ISSUE THREAD

**Issue by vigneshhari** [coronasafe/care#486]
Currently, all Permission management works by connecting to the M2M table, which. is extremely ineffective and can cause duplication, instead, we can split the permission management into two steps 
(1) Get the Facilities that the user has access to 
       * Skip this step and apply location filtering if the user is a State/District/LSG/Ward Admin
(2) Apply filters for this facility only

If possible cache the list of facilities the user has access to and then rebuild the cache on the facility user addition page. to not load up the DB further

**Comment by sainak** [comment]
to be implemented by #968
