### ISSUE TITLE
Api Endpoints

### ISSUE THREAD

**Issue by tomahawk-pilot** [coronasafe/care#49]
create api endpoints with GEt for count of facilities and staff

**Comment by vigneshhari** [comment]
Is this for the reports or for induvidual facilities ?

**Comment by biswaz** [comment]
@tomahawk-pilot @vigneshhari the later is already on master btw. if that is the case lets close this issues, otherwise lets open an issue with a detailed spec for reports

**Comment by vigneshhari** [comment]
Agree, let's close this and create a separate one for reports. @biswaz can you create the issues?
