### ISSUE TITLE
Add KSDMA logo to footer

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care#50]
Add KSDMA Logo 
![ksdma](https://user-images.githubusercontent.com/14979190/77244764-0f151200-6c3f-11ea-973b-e63fd6bf9896.png)

> Update footer text:
Corona Care is a part of the Corona Safe Network created as an open source platform by volunteers along with the State Sisaster Management Authority Government of Kerala.

**Comment by bodhish** [comment]
Check with me before merge

**Comment by jee1mr** [comment]
PR sent
