### ISSUE TITLE
Bed Capacity Form Validation

### ISSUE THREAD

**Issue by jee1mr** [coronasafe/care#53]
Shouldn't there be a check on Current Capacity Utilisation < Total Capacity?
<img width="545" alt="Screenshot 2020-03-22 at 2 25 18 PM" src="https://user-images.githubusercontent.com/6749387/77245990-14775a00-6c49-11ea-8aa8-a9d2a6fcd891.png">

**Comment by vigneshhari** [comment]
There should be a validation present, feel free to take up the issue and solve it.

**Comment by jee1mr** [comment]
On it
