### ISSUE TITLE
Create system to manage data processing from crowd sourced initiatives.

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care#537]
Context: https://github.com/coronasafe/features/issues/25

We should create a system where the admin could add a list of public google sheet links. 
The system should fetch the data from these sheets and write to the DB if there is a change in any of the fields. 

Schema for the sheet: https://docs.google.com/spreadsheets/d/1I_V1K4pEoz1omlMaYC7tZScMYMlGAYBXzVpuvspws7E/edit#gid=0

This is high priority. 

- [x] Create a mechanism to scrape data
- [x] create a summary endpoint that caches the data every x minutes
- [x] Add 2 endpoints to upvote and downvote each entry.

**Comment by technoknol** [comment]
@bodhish I've added Data Validation for Districts and States in sheet (Sample Sheet). Please add similar Data Validation for Resource Type and Category and lock **Category** sheet.

![image](https://user-images.githubusercontent.com/6429418/116199234-85464b00-a754-11eb-8ffe-e6ebf28df6ba.png)
![image](https://user-images.githubusercontent.com/6429418/116199378-ac048180-a754-11eb-9e8e-8cc8bfd3f3d0.png)

**Comment by bodhish** [comment]
Sure.

**Comment by vigneshhari** [comment]
Closing Issue since everything is implemented.
