### ISSUE TITLE
The links in About and Readme are not working 

### ISSUE THREAD

**Issue by ganeshsp1** [coronasafe/care#556]
The links in Readme page are not working :

Auto Deployed to https://careapi.coronasafe.in for master Branch.

Report bugs at https://bugs.coronasafe.in

The link in About is also not working :

care.coronasafe.network/

**Comment by ganeshsp1** [comment]
The sites come up without any issue in my mobile, this issue seems to be there when I access the site from my office laptop 

From the console I could see only the following error :

(index):5551 crbug/1173575, non-JS module files deprecated.
(anonymous) @ (index):5551

**Comment by vigneshhari** [comment]
VPN's are blocked by default in our WAF, JS is required to render all our pages. @tomahawk-pilot can help answer with more clarity.
