### ISSUE TITLE
Handle duplicate facility registration

### ISSUE THREAD

**Issue by shanavas786** [coronasafe/care#57]
It needs to handle duplication facility registration.

For hospitals and institution, corresponding registration number could be used as identifier.

**Comment by vigneshhari** [comment]
@bodhish are we allowed to take any sensitive info as such. ?

**Comment by bodhish** [comment]
I will check and get back on it

**Comment by AugustinJose1221** [comment]
> @bodhish are we allowed to take any sensitive info as such. ?

You can use latitude/longitude data if such sensitive data is not available

**Comment by shanavas786** [comment]
> @bodhish are we allowed to take any sensitive info as such. ?

I don't think it is as sensitive as phone number. We can make this field write only

**Comment by afzalIbnSH** [comment]
Any update on this? Shall I take up and add the field? If yes, someone please tell me how a registration number looks like so I could choose the suitable type.

**Comment by vigneshhari** [comment]
we have many hospitals already added in the system, making them add the hospital reg code is easy for us to do, but the folks adding the hospital also have to have the data which makes it hard. Once we confirm that they have the data of all hospitals we can continue. Please wait for @bodhish to confirm

**Comment by afzalIbnSH** [comment]
Can we just create a uniqueness constraint => `(name, district, facility_type)`

**Comment by vigneshhari** [comment]
Yes we can add a unique together filter.

**Comment by vigneshhari** [comment]
Closing this issue as Hospitals are instructed to create one facility for their data
