### ISSUE TITLE
All Api Responses to follow this structure

### ISSUE THREAD

**Issue by tomahawk-pilot** [coronasafe/care#59]
{
  "success": true/false,
  "message": "Success / message custom",
  "data": {
    
  }
}

**Comment by anroopak** [comment]
I can take this up

**Comment by afzalIbnSH** [comment]
Don't we have http status codes to imply success/failure ? :/

**Comment by vigneshhari** [comment]
we already have HTTP status codes to signify the success status and a message is sent whenever there is a message.

**Comment by vigneshhari** [comment]
data is sent over whenever a data-based CUD operations  are done, i believe that's how DRF operates

**Comment by tomahawk-pilot** [comment]
ok . got it
