### ISSUE TITLE
The API documentation is showing the enum fields as integers

### ISSUE THREAD

**Issue by afzalIbnSH** [coronasafe/care#64]
Eg:
![Screenshot 2020-03-22 at 9 33 13 PM](https://user-images.githubusercontent.com/45993339/77254070-c84a0b00-6c84-11ea-9377-f83574696b86.png)
The options are correct but the field type is wrong

**Comment by biswaz** [comment]
It can either show the int values (which is meaningless)  or verbose names.

**Comment by afzalIbnSH** [comment]
This is a wrong issue. Sorry for the confusion. The APIs accept the integers, so the field is correct.
