### ISSUE TITLE
Refactor to seperate models, serializers, viewsets into seperate files

### ISSUE THREAD

**Issue by anroopak** [coronasafe/care#65]
The models, serializer and viewsets files are growing. Each should be split and handled.

**Comment by anroopak** [comment]
@vigneshhari @biswaz shouldn't we do this?

**Comment by vigneshhari** [comment]
this would be a good idea, but for now, let the models remain in one file to avoid confusion as all of them are linked, once we start reporting and creating more complex views, we can split them into separate files.

**Comment by anroopak** [comment]
OK, moving the serializers and views, then?

**Comment by anroopak** [comment]
@vigneshhari this can be closed now.
