### ISSUE TITLE
Integrate with Middleware for Periodic Sync of Asset Information

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care#658]
Create CRON Jobs that would periodically update Patient Information after fetching data from the middleware

_This is a draft issue. Device Integrations that affect Patient Information needs to be triaged_

**Comment by bodhish** [comment]
@gigincg Middleware should update care in specific intervals.

**Comment by gigincg** [comment]
https://github.com/coronasafe/care/pull/811 Should Close this
