### ISSUE TITLE
Why is Skill field not visible in the staff signup form?

### ISSUE THREAD

**Issue by Kailaash-Balachandran** [coronasafe/care#69]
Even though Skill is defined in the CustomSignupForm in forms.py and in the User model, I don't see the field displayed in https://care.coronasafe.network/users/signup/staff/ page.

I'm looking into the code and I stumbled upon the above issue. Is it intentional (did I miss something) or a bug?

**Comment by biswaz** [comment]
It is only visible when form type is volunteer. S
