### ISSUE TITLE
Unit Tests for Everything

### ISSUE THREAD

**Issue by vigneshhari** [coronasafe/care#7]
Add unit tests for any and every code written in the back-end.

**Comment by nabhanabdulla** [comment]
Hi, I would like to add unit tests for the back-end code. Are there any guidelines or should a particular library be used?

**Comment by vigneshhari** [comment]
No, you are free to use any library,
PS, just ping me on slack if i don't reply here, as i may miss the GitHub notifications

**Comment by biswaz** [comment]
@nabhanabdulla 
https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/unit-tests/
https://www.django-rest-framework.org/api-guide/testing/

**Comment by nabhanabdulla** [comment]
Ok, got it @vigneshhari 

Thanks @biswaz, looking into it

**Comment by ja8zyjits** [comment]
@vigneshhari  It will be great if we have the slack channel mentioned in the README file.
Easy for new developers to connect.

**Comment by vigneshhari** [comment]
@ja8zyjits create an issue, take it up and submit a PR :) 
( use the slack badge if possible )

**Comment by afzalIbnSH** [comment]
Are you doing this @nabhanabdulla ?

**Comment by ja8zyjits** [comment]
I have a small suggestion to make. Since there are many modules, it will be
better if each one picks one and work on it. A single person may find it
too much. Further make sure to mention here which modules you are working
on, for the ease of others, and reduce duplication of work.

**Comment by afzalIbnSH** [comment]
@ja8zyjits I agree. Going ahead and adding tests for facility.

**Comment by nabhanabdulla** [comment]
@afzalIbnSH , No, I am trying to make sense of the project code. I am new to Django and is learning currently. 

As @ja8zyjits suggested I think it will be better to take up for different modules. Also, it will be great if you either of you could help me get started.

**Comment by vigneshhari** [comment]
Create another issue for doing a specific View Testing and Comment that you are doing it

**Comment by abhiabhi94** [comment]
Shall I start adding tests for the users application?

**Comment by vigneshhari** [comment]
You can test all the API Views
