### ISSUE TITLE
Add pre-commit hooks to maintain code styles

### ISSUE THREAD

**Issue by anroopak** [coronasafe/care#71]
Add some common code styles as pre-commit hooks. 

Proposed hooks - 

- trailing-whitespace
        name: trim trailing whitespace
        description: This hook trims trailing whitespace on files
        entry: trailing-whitespace-fixer
- check-merge-conflict
        name: check for merge conflict
        description: Prevent accidentally commiting files with merge conflicts.
- end-of-file-fixer
        name: fix end of files.
        description: Ensures that a file is either empty, or ends with one newline.
- seed-isort-config
        description: sorts the imports, hence consistency in the import statements
- isort
        description: additional to seed-isort-config
- black
       description: ensures that commits don't go through without specific coding style

**Comment by biswaz** [comment]
Might slow down rapid prototyping, but I'm open to adding this now rather than later. We can make it non intrusive for now. Just ran flake8 now, its mostly isort errors only.

**Comment by anroopak** [comment]
One good thing about adding this would be that when we have more devs, the merging would not pull us down. Currently flake8 just shows the errors. If we replace that with black, isort, seed-isort-config - these pre-commit hooks takes care of the file changes.

**Comment by biswaz** [comment]
Could you mind setting this up?

**Comment by anroopak** [comment]
https://github.com/fluxility/pre-commit-django-migrations/blob/master/.pre-commit-hooks.yaml
I would suggest that we add this also.

**Comment by anroopak** [comment]
Yep, almost done with this.

**Comment by vigneshhari** [comment]
@biswaz please check the issue and merge it ASAP , as we wait it gets harder
