### ISSUE TITLE
Revamp Assets to better support Integration Assets

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care#757]
The Assets Model and APIs need to be updated to improve the asset integration. The following items would cover the majority of the changes required
- [x] #758
- [x] #759
- [x] #799
- [x] #800
- [x] #801
- [x] Backend: Migrate asset.meta.middleware_address to facility.middleware_address

Related Frontend Issues are tracked at https://github.com/coronasafe/care_fe/issues/2430

> Do not Assign the issue to yourself! The subissues will be created when the blockers for them are complete!

**Comment by aparnacoronasafe** [comment]
align with #2212
