### ISSUE TITLE
Backend: Migration to change meta.camera_address to meta.local_ip_address

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care#759]

**Comment by rithviknishad** [comment]
@sainAk @iamsdas @vigneshhari Still receiving it as `meta.camera_address` :(

![image](https://user-images.githubusercontent.com/25143503/172047923-15a86fa7-e5d0-4f02-8f2a-5b7688dac1ef.png)

**Comment by iamsdas** [comment]
@rithviknishad Deployment waiting for review I guess.
https://github.com/coronasafe/care/runs/6553313671?check_suite_focus=true

**Comment by rithviknishad** [comment]
Closing as it's fixed.
![image](https://user-images.githubusercontent.com/25143503/175275818-f2c010b1-a6dc-47f8-a351-afe55d427a55.png)
