### ISSUE TITLE
Create an API for comupting capacity

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care#76]
- [ ] show current capacity vs utilization
- [ ] district wise capacity and utilization

**Comment by bobinson** [comment]
capacity or occupancy ? What would be the correct usage in this case ?

**Comment by anroopak** [comment]
show current capacity vs utilization - for a facility can be got from 
GET facility/{facility_id}/capacitry/
Response: 
```
{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
            "room_type": 1,
            "total_capacity": 10,
            "current_capacity": 5
        }
    ]
}
```

Note: This API is available here - https://github.com/coronasafe/care/pull/74

**Comment by anroopak** [comment]
API Design
GET /facility/utilisation/state/
Response
// 
{
   "results": [
        {
           "district_id": 13, 
           "district_name": "Kannur", 
           "utilisation": [
               {
                    "room_type": 1,
                    "total_capacity": 10,
                    "current_capacity": 5
                }
           ] 
       }
   ] 
}


API Design
GET /facility/utilisation/district/
Response
// 
{
   "results": [
        {
           "facility_id": 13, 
           "facility_name": "General Hospital", 
           "utilisation": [
               {
                    "room_type": 1,
                    "total_capacity": 10,
                    "current_capacity": 5
                }
           ] 
       }
   ] 
}

**Comment by anroopak** [comment]
API Design
GET /facility/utilisation/state/
Response
```
{
   "results": [
        {
           "district_id": 13, 
           "district_name": "Kannur", 
           "utilisation": [
               {
                    "room_type": 1,
                    "total_capacity": 10,
                    "current_capacity": 5
                }
           ] 
       }
   ] 
}
```


API Design
GET /facility/utilisation/district/
Response
```
{
   "results": [
        {
           "facility_id": 13, 
           "facility_name": "General Hospital", 
           "utilisation": [
               {
                    "room_type": 1,
                    "total_capacity": 10,
                    "current_capacity": 5
                }
           ] 
       }
   ] 
}
```

**Comment by vigneshhari** [comment]
We would need reporting on a different dyno/app, i will take up this and finish it up, relying on SQL summarisation for each call is going to become expensive really quickly.

**Comment by vigneshhari** [comment]
Moved to a Third Party Reporting API, closing the issue
