### ISSUE TITLE
Add an API Route for password change by the user

### ISSUE THREAD

**Issue by siddnikh** [coronasafe/care#779]
Need to make an API route that lets the user update their password. Needed to solve this issue: https://github.com/coronasafe/care_fe/issues/2459

**Comment by sainAk** [comment]
@siddnikh we can just fix the `UserSerializer` update method to handle password field changes, also make the password a writeonly field, by doing this we can just PATCH the password, I don't think there is a requirement for a separate endpoint.

**Comment by siddnikh** [comment]
@sainAk I ended up making another route because I was a little unsure about how to proceed. Please review it when you get a chance and tell me if there's some changes I need to add to do it how you suggested to.

**Comment by siddnikh** [comment]
Here's the PR that solves this issue: #797
