### ISSUE TITLE
Push notification key is invalid

### ISSUE THREAD

**Issue by rabilrbl** [coronasafe/care#782]
In my recent PR coronasafe/care_fe#2498, I worked on creating a function to remove the padding from key returned from the server for push notifications as push notification subscriptions weren't working as mentioned in coronasafe/care_fe#2360. However, It turns out the key returned from the server is invalid.

![image](https://user-images.githubusercontent.com/63334479/169987995-a8a4cd41-6542-4f8e-98ea-11d32978e2f0.png)

## Implementation
- try to encode and send the unpadded base64 key in the API response
- fix invalid key in settings `VAPID_PUBLIC_KEY` [here](https://github.com/coronasafe/care/blob/master/config/settings/base.py#L420)
- API viewset for sending the key is [here](https://github.com/coronasafe/care/blob/master/care/facility/api/viewsets/notification.py#L43)

**Comment by gigincg** [comment]
@rabilrbl Were you able to verify if the backend was returning the Default VAPID or a different one?

**Comment by rabilrbl** [comment]
@gigincg Yes, it's different, not default.

![image](https://user-images.githubusercontent.com/63334479/170858833-90eaeb2d-c01a-41f4-a734-c08f4399e838.png)

**Comment by gigincg** [comment]
@khavinshankar The updated VAPID Keys solve this right? Closing this, do reopen if you feel the need to
