### ISSUE TITLE
Generate reports

### ISSUE THREAD

**Issue by biswaz** [coronasafe/care#79]
Report generation triggered in regular intervals or using management commands.

Run aggregation queries for Facilities, doctors, bed counts grouping by district, types (doctor type, fac type).

Store this in a new model called Report, in a json field.

Phase 2
---

per facility aggregations like by, bed type, doctor type etc should be stored in another table, not report.

**Comment by biswaz** [comment]
Use a worker process to run this process

**Comment by NavenAllen** [comment]
I can do it. Can I take this up?

**Comment by vigneshhari** [comment]
This will be handled internally, @biswaz will take it up

**Comment by vigneshhari** [comment]
Reporting now handled by 3rd Party
