### ISSUE TITLE
Create an API for capturing patient details

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care#80]
# required fields.
- name: string (hash)
- age: positve int
- district_id: District.id
- panchayat_id: Panchayat.id
- ward: string ?
- Have you tavelled to a foreign country?: bool
- Travelled country: option(string)
- travel_history_dates: option(date)
- Are you experiencing any symptoms: bool
- symptoms: option [check question 9 in pdf]
- elderly_people_at_home: bool
- chronic_disease: option[check question 11 in pdf]
- undergoing_treatment: bool
- do_you_have_memedicines: bool
- anyone_with_fever_symptoms_at_home: bool
- number_of_people_with_fever_symptoms_at_home: positive int
- anyone_with_fever_symptoms_in_neighbourhood: bool
- number_of_people_with_fever_symptoms_in_neighbourhood: positive int
- attended_public_events: bool
- public_events_attended: optional(string)
- Add question 20/21

[isolation details form.pdf](https://github.com/coronasafe/care/files/4373469/isolation.details.form.pdf)
]

**Comment by shanavas786** [comment]
can we make use of http://portal.covid19india.org/ ?

**Comment by NavenAllen** [comment]
I am creating a new model with a foreign key to User and exposing an API to it, is that fine?

Also, have two doubts in the requirements:
- Should country travelled and history dates be arrays, history dates being an object that contains from and till when the person stayed or just the last country and the date of return?
- I can't read Malayalam, so it would be helpful if someone could translate the symptoms choices and the last two questions 

@vigneshhari @bodhish @tomahawk-pilot @biswaz

**Comment by tomahawk-pilot** [comment]
> can we make use of http://portal.covid19india.org/ ?

sorry that is not allowed.

**Comment by tomahawk-pilot** [comment]
![Screenshot 2020-03-24 at 2 20 55 PM](https://user-images.githubusercontent.com/11440246/77406537-cf832d00-6dda-11ea-91fd-084425015794.png)

we will release anonymized data API later. they can consume it if they want.

**Comment by NavenAllen** [comment]
@tomahawk-pilot how do I got about doing it then?

**Comment by bodhish** [comment]
Lets stop work on this issue for now. 

We would moslty be collecting this data using sprinklr plarform. 

https://developer.sprinklr.com/

**Comment by bodhish** [comment]
https://docs.google.com/document/d/108EIEw9rB-LMuzQ-vsZtdjyVJ0ECKk5exRYessMg5e0/edit?ts=5e79fc0b

**Comment by vigneshhari** [comment]
This issue has been closed as patient data structure has changed a lot
