### ISSUE TITLE
Home page broken in Firefox

### ISSUE THREAD

**Issue by pavanmehta91** [coronasafe/care#81]
https://prnt.sc/rlna4c.

**Comment by shanavas786** [comment]
I dont see any issues in firefox 73-64bit
@pavanmehta91 can you share your browser details. Also check for errors in javascript console

**Comment by pavanmehta91** [comment]
It's working now. I'm not sure what might have caused that. I failed to check the dev console back then. 
It can't be the network right? The Registration and Login buttons are not loaded with AJAX?

**Comment by pavanmehta91** [comment]
From the screenshot I can make out that CSS might not have loaded. Cos logo looks bigger in the screenshot than it's after the entire page is loaded now!

**Comment by rejuls** [comment]
Network issue ig.

**Comment by pavanmehta91** [comment]
That may be the case
