### ISSUE TITLE
Update to Postgres

### ISSUE THREAD

**Issue by cp-Coder** [coronasafe/care#827]
# Issue

## Changes

- [x] Remove the location field from migrations
- [x] Remove django-location-field package
- [x] Update dockerfile and settings to use __postgres__

## Depends

- [x] [pr#822](https://github.com/coronasafe/care/pull/822)

**Comment by cp-Coder** [comment]
dockerfile updated in PR #919

**Comment by vigneshhari** [comment]
Care no longer has PostGIS references.
