### ISSUE TITLE
showing password-reset email status success even when I don't have CARE user account. 

### ISSUE THREAD

**Issue by JAIMIN-CHOKHAWALA** [coronasafe/care#842]
**Describe the bug**
Even when I don't have account on CARE system, it is showing me "password reset link sent successfully" when I do forgot password on login page and then random username as input. 

**To Reproduce**
1. Go to "Authorized Login" page (login page)  
2. Click on "forgot password"
3. Write invalid/random Username to send email on associated email-address with that user. 
4. It shows success status "Password reset email sent" 

**Expected behavior**
Expected status should be "Invalid user" OR "User not available in database"

**Screenshots**
![main](https://user-images.githubusercontent.com/66988372/172712930-d4200e64-79e7-47d6-9d0b-4686c0cbc701.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Brave
 - Version latest

**Additional context**
It looks like this is a frontend issue. I don't have any registered account on the CARE system, so it is not possible that my user is already available in the database. hence it is not possible to send me a password reset link  and it did not. So, it looks like it received "success" status on the frontend and showed me "password reset email sent".

**Comment by Marmik2003** [comment]
@JAIMIN-CHOKHAWALA I think the current way is a good way from security perspective... This way, we can be ensure that no one can apply the bruteforce techniques to find existing users and send spams or apply other attacks, yes... but I agree that the message should be changed to **"Password reset email will be sent shortly if account exists"**

**Comment by skks1212** [comment]
Yep, we have to make sure that all user information is intact.
The text on the forgot password page has been changed in PR [care_fe #2665](https://github.com/coronasafe/care_fe/pull/2665)

**Comment by sainAk** [comment]
closing this issue as it's being tracked in https://github.com/coronasafe/care_fe/issues/2664

**Comment by JAIMIN-CHOKHAWALA** [comment]
@sainAk, Yeah sure it is better to close it but I also with @Marmik2003 about changing status message.

**Comment by sainAk** [comment]
@JAIMIN-CHOKHAWALA https://github.com/coronasafe/care_fe/pull/2665 will update the status message
