### ISSUE TITLE
A patient can be switched to same bed at which he/she before was

### ISSUE THREAD

**Issue by patelaryan7751** [coronasafe/care#850]
# Bugs

## A patient can be switched to the same bed at which he/she before was

https://user-images.githubusercontent.com/59426397/173169660-b5446de4-637c-41af-a51d-c067cd92da2e.mp4

**Comment by aparnacoronasafe** [comment]
Multiple people can be assigned to the same bed.

Eg: https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patients
2 patients are assigned to Bed10- 10bedicu.

Add rule that if a bed is occupied by any patient, that bed must not appear as an option in the dropdown in "Assign bed" window.
