### ISSUE TITLE
More Fields to be added in Consultation Api

### ISSUE THREAD

**Issue by patelaryan7751** [coronasafe/care#859]
Part of [#2218](https://github.com/coronasafe/care_fe/issues/2218)
2 collapsable sections would be added to the consultation form **Health Section** and **Medical History** extra fields need to be added as the information given in the issue [#2218](https://github.com/coronasafe/care_fe/issues/2218)

**Comment by nihal467** [comment]
@cp-Coder Due to inactivity and the existing linked PR is not mergeable, unlinking you from this issue

As per the communication with @aparnacoronasafe , it will be sub-grouped with events module, so for time-being closing this issue
