### ISSUE TITLE
While Creating Daily Rounds the created_by field is null and doesnot display on Update Log

### ISSUE THREAD

**Issue by patelaryan7751** [coronasafe/care#879]
# Bugs

## While Creating Daily Rounds the created_by field is null and does not display on Update Log
https://user-images.githubusercontent.com/59426397/174632291-74795247-02e3-494d-b5b8-410617794af1.mp4

**Comment by cp-Coder** [comment]
@vigneshhari There is some problem in the code. That's why I have opened this issue.
