### ISSUE TITLE
add google analytics tag at root

### ISSUE THREAD

**Issue by tomahawk-pilot** [coronasafe/care#88]
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-160173841-21"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-160173841-21');
</script>

**Comment by vigneshhari** [comment]
I will add in base , can you add in the react app as well ?
