### ISSUE TITLE
API to retrieve facility summary data for card in all facilities page

### ISSUE THREAD

**Issue by patelaryan7751** [coronasafe/care#881]
API needed to add facility icons on the facility page for the issue https://github.com/coronasafe/care_fe/issues/2759

**Comment by Marmik2003** [comment]
Is facility icon the same as facility cover image or different: https://github.com/coronasafe/care/pull/791 ?

**Comment by patelaryan7751** [comment]
No, it is different. It's just the icons

**Comment by sainAk** [comment]
> Is facility icon the same as facility cover image or different: #791 ?

@Marmik2003 this api is needed to give out the summary for indicators mentioned  in care_fe#2759

**Comment by rithviknishad** [comment]
Closing as parent issue was closed as not planned
