### ISSUE TITLE
Issue with requirements

### ISSUE THREAD

**Issue by abhiabhi94** [coronasafe/care#89]
After successfully running the command
```
pip -r requirements.txt
```
and installing everything successfully. When I try to run a command
```
python manage.py createsuperuser
```
I get an error:
```
ModuleNotFoundError: No module named 'debug_toolbar'
```
I think we need to add `debug_toolbar` to requirements.txt somewhere.
Also, the project installed `sentry` during development, I don't think we need `sentry` for development.

**Comment by justinjohnymathew** [comment]
@abhiabhi94  Refer [this link](https://cookiecutter-django.readthedocs.io/en/latest/developing-locally.html)
This project uses cookiecutter

**Comment by rejuls** [comment]
Please use
pip install -r requirements/local.txt
