### ISSUE TITLE
Filter malfunction on /patients

### ISSUE THREAD

**Issue by kunatastic** [coronasafe/care#907]
![image](https://user-images.githubusercontent.com/61267953/177023281-c74f6e41-72e9-47eb-a1fb-cc45bd41809f.png)

Related coronasafe/care_fe#2981

**Comment by Ashesh3** [comment]
Related: https://github.com/coronasafe/care_fe/issues/2642 https://github.com/coronasafe/care_fe/pull/2659

**Comment by cp-Coder** [comment]
Closes with #841

**Comment by vigneshhari** [comment]
@kunatastic Close this issue if its resolved.
