### ISSUE TITLE
Facility bulk upsert lets user A update user B's facility

### ISSUE THREAD

**Issue by afzalIbnSH** [coronasafe/care#91]
Think this is a bug. Please confirm @vigneshhari @biswaz. If it is please assign me this issue, I shall fix it. Else you may close it.

**Comment by vigneshhari** [comment]
Yes you may fix this issue.

**Comment by anroopak** [comment]
@afzalIbnSH Make sure that the you don't restrict the superuser from overriding. In SuperUser's case, I feel that the existing ones' `created_by` need not be updated.
