### ISSUE TITLE
Constraint: AssetBed Relations

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care#934]
Currently AssetBed Relations are ManyToMany. Even though the Relation should work the same, we need to enforce constraints for this.

 - HL7Monitor Assets can have only 1 Bed Associated with it.
 - ONVIFCamera Assets can have multiple beds associated with it. One Bed Can have multiple Assets too
 - Assets that are neither HL7Monitor nor ONVIFCamera should not have Bed Relations

cc: @vigneshhari

**Comment by sainak** [comment]
fixed in #1524
