### ISSUE TITLE
Facility bulk upsert: Unable to add location

### ISSUE THREAD

**Issue by afzalIbnSH** [coronasafe/care#94]
![Screenshot 2020-03-25 at 1 36 13 PM](https://user-images.githubusercontent.com/45993339/77514897-9fe92900-6e9d-11ea-920f-0b61cc572f8e.png)

**Comment by afzalIbnSH** [comment]
I can fix this

**Comment by anroopak** [comment]
Please make sure that it is a non-required field. The API is mostly used by a tool to bulk upload data, which may not have the Location data

**Comment by afzalIbnSH** [comment]
Since the admins seems to be busy and I might get busy later, I'm going ahead and doing this.

**Comment by vigneshhari** [comment]
@anroopak check if the problem is fixed , if so i'll close the issue

**Comment by anroopak** [comment]
@vigneshhari verified
