### ISSUE TITLE
KeyError: "Key 'skill' not found

### ISSUE THREAD

**Issue by andy1729** [coronasafe/care#95]
```python
KeyError: "Key 'skill' not found in 'CustomSignupForm'. Choices are: age, district, email, first_name, gender, last_name, password1, password2, phone_number, username."
```
This error happened while processing signup form!

This issue seems obvious as 'skill' being a ForeignKey to User model, it should be represented by django.forms.ModelChoiceField.

*Edit
Was wrong about this!

**Comment by biswaz** [comment]
Please give us the full traceback, always.

**Comment by andy1729** [comment]
Sorry!
Here it is!
```python
Traceback (most recent call last):
  File "/Users/andy1729/.pyenv/versions/care/lib/python3.7/site-packages/crispy_forms/utils.py", line 70, in render_field
    bound_field = form[field]
  File "/Users/andy1729/.pyenv/versions/care/lib/python3.7/site-packages/django/forms/forms.py", line 169, in __getitem__
    ', '.join(sorted(f for f in self.fields)),
KeyError: "Key 'skill' not found in 'CustomSignupForm'. Choices are: age, district, email, first_name, gender, last_name, password1, password2, phone_number, username."
```

**Comment by vigneshhari** [comment]
@biswaz please look into it , I am assigning you to this

**Comment by rejuls** [comment]
This is happening because we decided to remove that field on signup forms other than the volunteer one. Since we are using the same form class for all 3, crispy forms is looking for the field but it is being popped.

**Comment by andy1729** [comment]
> This is happening because we decided to remove that field on signup forms other than the volunteer one. Since we are using the same form class for all 3, crispy forms is looking for the field but it is being popped.

Yes, indeed!
Adding
```python 
form.helper.layout.pop(8) # 8 being index of skill
```
after popping 'skill' from form fields will resolve this issue!

**Comment by rejuls** [comment]
Solved
