### ISSUE TITLE
Allow Maintainers other than Creators

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care#97]
The data is mostly entered in bulk and needs to be editable by maintainers other than the person who created it. We need a dashboard that can allow allotting a set of maintainers to a facilities and allow those maintainers to update the data.

**Comment by afzalIbnSH** [comment]
This should be accessible only to admins right? An admin shall allot maintainers, right ? I guess we should add an additional field and not replace the `created_by` field since
- Calling someone the creater when he didn't create the facility is false information and
- It could be helpful to know later on who created a facility.

**Comment by vigneshhari** [comment]
but this should only be allowed to be used by a superuser or a superadmin ,

**Comment by vigneshhari** [comment]
@afzalIbnSH we can create another field like uploaded by,  only uploaded facility should be moved to another user.

**Comment by afzalIbnSH** [comment]
Yea. I meant a superuser. Not a hospital admin.

**Comment by afzalIbnSH** [comment]
I think a superuser should be able to move the ownership of any facility. Maybe we add a field `maintainer` refering the user table. By default it's the creator and a superuser should be able to change that to another user. Makes sense ?

**Comment by afzalIbnSH** [comment]
I can make the API changes for this.

**Comment by vigneshhari** [comment]
We already have this in the admin pannel

**Comment by anroopak** [comment]
I feel that the problem @gigincg is pointing out is that 1 person will create the data. But it would be someone else who changes / updates the info. In the current system, only the person who created can make the changes (and admin). Problem with current approach is that once we start hitting scale within a few days, updating will cause issues. So I feel that restrictions should be at district level and not at a user level.

**Comment by vigneshhari** [comment]
@anroopak Once the hospital admins are added this will no longer be an issue, The hospitals are almost completely registered, i believe if the local team can correct the users using the admin panel is the best way to solve it, we need to ensure we have strict policies for managing data, Admin Panel has a history that stores any and all changes built-in.  
Patient data is extremely sensitive and we need to ensure that there are all kinds of restrictions for who gets to handle it, even it means more hardship for us or the local team.
