### ISSUE TITLE
Admin Search Filter

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care#98]
Superuser unable to search using filters. Filters like District for Facility for instance are necessary for maintaining data. 

Edit: Also Facility Capacities are completely unsearchable. Need to make it linked to Facility Object or at least make Facility Capacity entries searchable by Facility Name.

**Comment by abinmn** [comment]
Can I take this?

**Comment by vigneshhari** [comment]
Yeah Sure

**Comment by abinmn** [comment]
I think #105 fixes this.

**Comment by vigneshhari** [comment]
@abinmn it does not have a filter yet, we need to add filters based on this model, for eg , filter facility by dist ,state  and so on ..

**Comment by vigneshhari** [comment]
dont add panchayath level sorting as it may crash the admin

**Comment by abinmn** [comment]
By providing `district_name` as the query param, users can filter the facility. Also, he has implemented the same for the ambulance viewset.

https://github.com/coronasafe/care/blob/c21077777af6ba991d40074092970daa03f9b6c5/care/facility/api/viewsets/facility.py#L16-L27

**Comment by gigincg** [comment]
Added Edits for Additional Filters Required

**Comment by agzuniverse** [comment]
I'll work on this.

**Comment by vivekc0des** [comment]
Is this still not fixed?

**Comment by agzuniverse** [comment]
@vigneshhari this issue is not completely fixed since it mentions we need filter by facility capacity. My PR #208 only fixed filter by district and local body name and IDs.
