### ISSUE TITLE
Bug: User registration

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care#980]
**Describe the bug**
When I  try to register a district admin user with the username "james", something went wrong error comes up

**To Reproduce**
Login as a district admin
go to create user
fill in details as shown in the video. he username must be "james'

**Expected behavior**
a new user must be registered

**Recording**

Uploading Bug-user registration.mov…

**Desktop (please complete the following information):**
 - Mac OS chrome 

**Additional context**
when I edited the username to "james@111" or "james@123", it worked fine

**Comment by vigneshhari** [comment]
@aparnacoronasafe, a user with the same username exists, this is why the backend threw an error, let's modify this issue to add a cleaner error when this happens.
Actual error : `duplicate key value violates unique constraint "users_user_username_key" DETAIL: Key (username)=(james) already exists`

**Comment by aparnacoronasafe** [comment]
@vigneshhari Currently we do have a Username availability check happening on the UI itself. That said that the username is available. 

We need to make that availability check more accurate.

Can you guys file an issue? @vigneshhari @gigincg @khavinshankar ? and then close this issue?

**Comment by vigneshhari** [comment]
Backend never really built a feature to check if a username is available, this is working on some hack, it was never an intended feature

**Comment by aparnacoronasafe** [comment]
@vigneshhari can we have an issue for that?

**Comment by vigneshhari** [comment]
You can create one.

**Comment by aparnacoronasafe** [comment]
https://github.com/coronasafe/care/issues/989 @vigneshhari 

Created one in care repo. Is there anything to be done on the FE? Should we close this issue?
