### ISSUE TITLE
Bug: Asset Creation UI

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care#983]
**Describe the bug**
When in asset registration form (https://care.coronasafe.in/facility/3447b03d-7522-4525-9e14-58d7628b1e9e/assets/new) and I click on Working status, The drop down appears. but the layout of the entire page shifts to the left to accommodate the drowpdown

**To Reproduce**
1. Go to asset registration form
2. Click on working status

**Expected behavior**
The layout must remain steady and the dropdown must allign as per design of the page

**Recording**

https://user-images.githubusercontent.com/67050716/185619981-3dfa5800-ea34-4250-b3ac-3aa333bae980.mov

**Desktop (please complete the following information):**
 - OS: [e.g. Mac OS]
 - Browser [chrome,]

**Comment by cp-Coder** [comment]
@aparnacoronasafe This is a frontend issue and also @nihal467 opened a similar issue  coronasafe/care_fe#3265. Also a PR coronasafe/care_fe#3266 related to this issue is already in progress

**Comment by aparnacoronasafe** [comment]
@cp-Coder Thanks for pointing it out. I will be more careful in checking if an issue is already filed.
