### ISSUE TITLE
No facility data found on time of New user registration.

### ISSUE THREAD

**Issue by Jrl0** [coronasafe/care#985]
When I try to create a care account for a doctor . No facilities are to be found on the time of user registration.
My role is State admin.
Time of incident occured 20 Aug. Around 3:00pm.
Screen record video attached.

Regards 
Jamesreeves
Care Manipur state admin

**Comment by nihal467** [comment]
issue is resolved

**Comment by sainak** [comment]
@Jrl0, @aparnacoronasafe please check the state of this issue once more and reopen if it still exists
