### ISSUE TITLE
Pressure Sore: Enhancement (PUSH score)

### ISSUE THREAD

**Issue by arpancodes** [coronasafe/care#986]
Refer: https://github.com/coronasafe/care_fe/issues/3432
Need to add 
- [ ] Length - number
- [ ] Width - number
- [ ] Exudate Amount - string, ENUM: None, Light, Moderate, Heavy
- [ ] Tissue Type - String, ENUM: Closed, Epithelial tissue, Granulation Tissue, Slough, Necrotic tissue
- [ ] Description - String
- [ ] Push score - number, calculated on the backend 

scores should be based on the following table:
![image](https://user-images.githubusercontent.com/42417893/185783545-2c7ab666-667d-4442-bbc7-65f40d360d4c.png)

**Comment by aparnacoronasafe** [comment]
Clarification:

A suggestive design would be something like this
<img width="734" alt="Screenshot 2022-08-26 at 8 18 31 PM" src="https://user-images.githubusercontent.com/67050716/186932068-ae57c78e-6717-40b5-834f-ed5c93369a8d.png">
