### ISSUE TITLE
Check availability of username

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care#989]
Build a test to check availability of username to be placed in the User creation page

**Comment by Ashesh3** [comment]
@siddnikh Hey, are you currently working on this PR?

**Comment by siddnikh** [comment]
@Ashesh3 hi! No, I'm not. Please go ahead.

**Comment by rithviknishad** [comment]
@siddnikh use closing keywords when linking PRs with issues when the PR achieves the requirements in the issue.
