### ISSUE TITLE
Add tables for state, district and panchayat

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care#99]
- [x] Add colum for panchayat in facility. 
- [x] Seed data for kerala
- [x] Migrate Existing Data

**Comment by vigneshhari** [comment]
We need to write custom migrations to update the current district field to the new table as well,  We need to have API's to get the districts under the state and so on ..

**Comment by vigneshhari** [comment]
@bodhish can we get an initial dataset for the models?  @tomahawk-pilot do you have it ?

**Comment by anroopak** [comment]
I can pickup :raised_back_of_hand:

**Comment by vigneshhari** [comment]
@afzalIbnSH you can also pitch in and solve some parts parallelly so we can push to production faster, you guys can collaborate

**Comment by anroopak** [comment]
When you say, I am assuming that it is the Local Body (Panchayath / Municipality / Corportation)
Do we need a Ward level info?

**Comment by vigneshhari** [comment]
@bodhish Please confirm

**Comment by bodhish** [comment]
we just need panchayat details.

**Comment by anroopak** [comment]
@bodhish there are hospitals which are inside Municipalites and Corporations? I feel we can generalise at "Local Body" levels.

**Comment by bodhish** [comment]
My understanding about the organization is completely wrong.

**Comment by anroopak** [comment]
Strategy for migration

First PR
1. will create the models, existing district field will not be removed, new field will be added.
2. add districts
3. populate the existing tables with district objects. 

Second PR (after the first PR is merged and released)
1. Remove the earlier district column
2. Rename the newly added district column to existing `district` column

**Comment by anroopak** [comment]
PRs raised. @vigneshhari Review please.
Only list and retrieve APIs are posted for the new entities. 
Filters based on District and Local Body names have been added to Facility and Ambulance.

**Comment by anroopak** [comment]
Facility Create
/facility/
{
  ...existing fields
  "local_body": id, 
  "district": id,
   "state": id
}

List/Detail
{
   ...existing,
   // only state will not be null, others can be null considering the data the states give
   "local_body": id,
   "local_body_object": {
          "id",
          "name", 
          "district": id
       },
    "district": id
    "district_object": {
          "id",
          "name", 
          "state": id
       },
     "state": id,
    "state_object": {
          "id",
          "name"
       }
 
}
